//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinoSystemWatch.SinoMoniterCommand {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SinoMoniterCommand.ISinoMonitorCommand")]
    public interface ISinoMonitorCommand {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISinoMonitorCommand/DoCommand", ReplyAction="http://tempuri.org/ISinoMonitorCommand/DoCommandResponse")]
        byte[] DoCommand(string UserPass, string CommandName, string DesServer, byte[] ParameterData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISinoMonitorCommandChannel : SinoSystemWatch.SinoMoniterCommand.ISinoMonitorCommand, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SinoMonitorCommandClient : System.ServiceModel.ClientBase<SinoSystemWatch.SinoMoniterCommand.ISinoMonitorCommand>, SinoSystemWatch.SinoMoniterCommand.ISinoMonitorCommand {
        
        public SinoMonitorCommandClient() {
        }
        
        public SinoMonitorCommandClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SinoMonitorCommandClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SinoMonitorCommandClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SinoMonitorCommandClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] DoCommand(string UserPass, string CommandName, string DesServer, byte[] ParameterData) {
            return base.Channel.DoCommand(UserPass, CommandName, DesServer, ParameterData);
        }
    }
}
