//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinoSZClientSysManager.JSGeneralDataService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JSGeneralDataService.IJSGeneralDataService")]
    public interface IJSGeneralDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJSGeneralDataService/Do", ReplyAction="http://tempuri.org/IJSGeneralDataService/DoResponse")]
        string Do(string Token, string CommandName, string XmlData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJSGeneralDataServiceChannel : SinoSZClientSysManager.JSGeneralDataService.IJSGeneralDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JSGeneralDataServiceClient : System.ServiceModel.ClientBase<SinoSZClientSysManager.JSGeneralDataService.IJSGeneralDataService>, SinoSZClientSysManager.JSGeneralDataService.IJSGeneralDataService {
        
        public JSGeneralDataServiceClient() {
        }
        
        public JSGeneralDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JSGeneralDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JSGeneralDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JSGeneralDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Do(string Token, string CommandName, string XmlData) {
            return base.Channel.Do(Token, CommandName, XmlData);
        }
    }
}
