//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinoSysWatchService.Application.SinoSZJSCommonService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SinoOrganize", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.Authorize")]
    [System.SerializableAttribute()]
    public partial class SinoOrganize : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanSelecetedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DWDMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DisplayOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FatherCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunctionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanSeleceted {
            get {
                return this.CanSelecetedField;
            }
            set {
                if ((this.CanSelecetedField.Equals(value) != true)) {
                    this.CanSelecetedField = value;
                    this.RaisePropertyChanged("CanSeleceted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DWDM {
            get {
                return this.DWDMField;
            }
            set {
                if ((object.ReferenceEquals(this.DWDMField, value) != true)) {
                    this.DWDMField = value;
                    this.RaisePropertyChanged("DWDM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisplayOrder {
            get {
                return this.DisplayOrderField;
            }
            set {
                if ((this.DisplayOrderField.Equals(value) != true)) {
                    this.DisplayOrderField = value;
                    this.RaisePropertyChanged("DisplayOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FatherCode {
            get {
                return this.FatherCodeField;
            }
            set {
                if ((this.FatherCodeField.Equals(value) != true)) {
                    this.FatherCodeField = value;
                    this.RaisePropertyChanged("FatherCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Function {
            get {
                return this.FunctionField;
            }
            set {
                if ((object.ReferenceEquals(this.FunctionField, value) != true)) {
                    this.FunctionField = value;
                    this.RaisePropertyChanged("Function");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerConfig", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.Config")]
    [System.SerializableAttribute()]
    public partial class ServerConfig : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Client_ShowPendingAlertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RemoteRenewValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RootOrgIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Client_ShowPendingAlert {
            get {
                return this.Client_ShowPendingAlertField;
            }
            set {
                if ((this.Client_ShowPendingAlertField.Equals(value) != true)) {
                    this.Client_ShowPendingAlertField = value;
                    this.RaisePropertyChanged("Client_ShowPendingAlert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RemoteRenewValue {
            get {
                return this.RemoteRenewValueField;
            }
            set {
                if ((this.RemoteRenewValueField.Equals(value) != true)) {
                    this.RemoteRenewValueField = value;
                    this.RaisePropertyChanged("RemoteRenewValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RootOrgID {
            get {
                return this.RootOrgIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RootOrgIDField, value) != true)) {
                    this.RootOrgIDField = value;
                    this.RaisePropertyChanged("RootOrgID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SinoMenuItem", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.MenuType")]
    [System.SerializableAttribute()]
    public partial class SinoMenuItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanUseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SinoSysWatchService.Application.SinoSZJSCommonService.SinoMenuItem[] ChildrenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DisplayOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FatherIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IconIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IconNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenuIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenuParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenuTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenuTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanUse {
            get {
                return this.CanUseField;
            }
            set {
                if ((this.CanUseField.Equals(value) != true)) {
                    this.CanUseField = value;
                    this.RaisePropertyChanged("CanUse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SinoSysWatchService.Application.SinoSZJSCommonService.SinoMenuItem[] Children {
            get {
                return this.ChildrenField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildrenField, value) != true)) {
                    this.ChildrenField = value;
                    this.RaisePropertyChanged("Children");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisplayOrder {
            get {
                return this.DisplayOrderField;
            }
            set {
                if ((this.DisplayOrderField.Equals(value) != true)) {
                    this.DisplayOrderField = value;
                    this.RaisePropertyChanged("DisplayOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FatherID {
            get {
                return this.FatherIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FatherIDField, value) != true)) {
                    this.FatherIDField = value;
                    this.RaisePropertyChanged("FatherID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IconIndex {
            get {
                return this.IconIndexField;
            }
            set {
                if ((object.ReferenceEquals(this.IconIndexField, value) != true)) {
                    this.IconIndexField = value;
                    this.RaisePropertyChanged("IconIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IconName {
            get {
                return this.IconNameField;
            }
            set {
                if ((object.ReferenceEquals(this.IconNameField, value) != true)) {
                    this.IconNameField = value;
                    this.RaisePropertyChanged("IconName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Level {
            get {
                return this.LevelField;
            }
            set {
                if ((this.LevelField.Equals(value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuID {
            get {
                return this.MenuIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuIDField, value) != true)) {
                    this.MenuIDField = value;
                    this.RaisePropertyChanged("MenuID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuParameter {
            get {
                return this.MenuParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuParameterField, value) != true)) {
                    this.MenuParameterField = value;
                    this.RaisePropertyChanged("MenuParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuTitle {
            get {
                return this.MenuTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuTitleField, value) != true)) {
                    this.MenuTitleField = value;
                    this.RaisePropertyChanged("MenuTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuType {
            get {
                return this.MenuTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuTypeField, value) != true)) {
                    this.MenuTypeField = value;
                    this.RaisePropertyChanged("MenuType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="firstPageItem", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.MenuType")]
    [System.SerializableAttribute()]
    public partial class firstPageItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemParamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Caption {
            get {
                return this.CaptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CaptionField, value) != true)) {
                    this.CaptionField = value;
                    this.RaisePropertyChanged("Caption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemParam {
            get {
                return this.ItemParamField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemParamField, value) != true)) {
                    this.ItemParamField = value;
                    this.RaisePropertyChanged("ItemParam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemType {
            get {
                return this.ItemTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemTypeField, value) != true)) {
                    this.ItemTypeField = value;
                    this.RaisePropertyChanged("ItemType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserLogRecord", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.UserLog")]
    [System.SerializableAttribute()]
    public partial class UserLogRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CZLXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CZNRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CZSJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserHostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CZLX {
            get {
                return this.CZLXField;
            }
            set {
                if ((object.ReferenceEquals(this.CZLXField, value) != true)) {
                    this.CZLXField = value;
                    this.RaisePropertyChanged("CZLX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CZNR {
            get {
                return this.CZNRField;
            }
            set {
                if ((object.ReferenceEquals(this.CZNRField, value) != true)) {
                    this.CZNRField = value;
                    this.RaisePropertyChanged("CZNR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CZSJ {
            get {
                return this.CZSJField;
            }
            set {
                if ((this.CZSJField.Equals(value) != true)) {
                    this.CZSJField = value;
                    this.RaisePropertyChanged("CZSJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IpAddress {
            get {
                return this.IpAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IpAddressField, value) != true)) {
                    this.IpAddressField = value;
                    this.RaisePropertyChanged("IpAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginName {
            get {
                return this.LoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginNameField, value) != true)) {
                    this.LoginNameField = value;
                    this.RaisePropertyChanged("LoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((this.ResultTypeField.Equals(value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultTypeName {
            get {
                return this.ResultTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultTypeNameField, value) != true)) {
                    this.ResultTypeNameField = value;
                    this.RaisePropertyChanged("ResultTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserHost {
            get {
                return this.UserHostField;
            }
            set {
                if ((object.ReferenceEquals(this.UserHostField, value) != true)) {
                    this.UserHostField = value;
                    this.RaisePropertyChanged("UserHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemLogRecord", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.SystemLog")]
    [System.SerializableAttribute()]
    public partial class SystemLogRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CZSJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CZSJ {
            get {
                return this.CZSJField;
            }
            set {
                if ((this.CZSJField.Equals(value) != true)) {
                    this.CZSJField = value;
                    this.RaisePropertyChanged("CZSJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogText {
            get {
                return this.LogTextField;
            }
            set {
                if ((object.ReferenceEquals(this.LogTextField, value) != true)) {
                    this.LogTextField = value;
                    this.RaisePropertyChanged("LogText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogType {
            get {
                return this.LogTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.LogTypeField, value) != true)) {
                    this.LogTypeField = value;
                    this.RaisePropertyChanged("LogType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotifyInfo", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.Notify")]
    [System.SerializableAttribute()]
    public partial class NotifyInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FBdwidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FBdwmcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FByhidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FByhmcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SendTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Context {
            get {
                return this.ContextField;
            }
            set {
                if ((object.ReferenceEquals(this.ContextField, value) != true)) {
                    this.ContextField = value;
                    this.RaisePropertyChanged("Context");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FBdwid {
            get {
                return this.FBdwidField;
            }
            set {
                if ((object.ReferenceEquals(this.FBdwidField, value) != true)) {
                    this.FBdwidField = value;
                    this.RaisePropertyChanged("FBdwid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FBdwmc {
            get {
                return this.FBdwmcField;
            }
            set {
                if ((object.ReferenceEquals(this.FBdwmcField, value) != true)) {
                    this.FBdwmcField = value;
                    this.RaisePropertyChanged("FBdwmc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FByhid {
            get {
                return this.FByhidField;
            }
            set {
                if ((object.ReferenceEquals(this.FByhidField, value) != true)) {
                    this.FByhidField = value;
                    this.RaisePropertyChanged("FByhid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FByhmc {
            get {
                return this.FByhmcField;
            }
            set {
                if ((object.ReferenceEquals(this.FByhmcField, value) != true)) {
                    this.FByhmcField = value;
                    this.RaisePropertyChanged("FByhmc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SendTime {
            get {
                return this.SendTimeField;
            }
            set {
                if ((this.SendTimeField.Equals(value) != true)) {
                    this.SendTimeField = value;
                    this.RaisePropertyChanged("SendTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelNum {
            get {
                return this.TelNumField;
            }
            set {
                if ((object.ReferenceEquals(this.TelNumField, value) != true)) {
                    this.TelNumField = value;
                    this.RaisePropertyChanged("TelNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrgExtFieldDefine", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.OrganizeExt")]
    [System.SerializableAttribute()]
    public partial class OrgExtFieldDefine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayTitle {
            get {
                return this.DisplayTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayTitleField, value) != true)) {
                    this.DisplayTitleField = value;
                    this.RaisePropertyChanged("DisplayTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldName {
            get {
                return this.FieldNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldNameField, value) != true)) {
                    this.FieldNameField = value;
                    this.RaisePropertyChanged("FieldName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldType {
            get {
                return this.FieldTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldTypeField, value) != true)) {
                    this.FieldTypeField = value;
                    this.RaisePropertyChanged("FieldType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrgExtInfo", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.OrganizeExt")]
    [System.SerializableAttribute()]
    public partial class OrgExtInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ExtPropertiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ExtProperties {
            get {
                return this.ExtPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtPropertiesField, value) != true)) {
                    this.ExtPropertiesField = value;
                    this.RaisePropertyChanged("ExtProperties");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SinoTaskInfo", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.TaskInfo")]
    [System.SerializableAttribute()]
    public partial class SinoTaskInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NextTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RWIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RWLXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RWMCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RWMLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RWMSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RWZTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RunFlagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastResult {
            get {
                return this.LastResultField;
            }
            set {
                if ((object.ReferenceEquals(this.LastResultField, value) != true)) {
                    this.LastResultField = value;
                    this.RaisePropertyChanged("LastResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastTime {
            get {
                return this.LastTimeField;
            }
            set {
                if ((this.LastTimeField.Equals(value) != true)) {
                    this.LastTimeField = value;
                    this.RaisePropertyChanged("LastTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NextTime {
            get {
                return this.NextTimeField;
            }
            set {
                if ((this.NextTimeField.Equals(value) != true)) {
                    this.NextTimeField = value;
                    this.RaisePropertyChanged("NextTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RWID {
            get {
                return this.RWIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RWIDField, value) != true)) {
                    this.RWIDField = value;
                    this.RaisePropertyChanged("RWID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RWLX {
            get {
                return this.RWLXField;
            }
            set {
                if ((object.ReferenceEquals(this.RWLXField, value) != true)) {
                    this.RWLXField = value;
                    this.RaisePropertyChanged("RWLX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RWMC {
            get {
                return this.RWMCField;
            }
            set {
                if ((object.ReferenceEquals(this.RWMCField, value) != true)) {
                    this.RWMCField = value;
                    this.RaisePropertyChanged("RWMC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RWML {
            get {
                return this.RWMLField;
            }
            set {
                if ((object.ReferenceEquals(this.RWMLField, value) != true)) {
                    this.RWMLField = value;
                    this.RaisePropertyChanged("RWML");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RWMS {
            get {
                return this.RWMSField;
            }
            set {
                if ((object.ReferenceEquals(this.RWMSField, value) != true)) {
                    this.RWMSField = value;
                    this.RaisePropertyChanged("RWMS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RWZT {
            get {
                return this.RWZTField;
            }
            set {
                if ((object.ReferenceEquals(this.RWZTField, value) != true)) {
                    this.RWZTField = value;
                    this.RaisePropertyChanged("RWZT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RunFlag {
            get {
                return this.RunFlagField;
            }
            set {
                if ((object.ReferenceEquals(this.RunFlagField, value) != true)) {
                    this.RunFlagField = value;
                    this.RaisePropertyChanged("RunFlag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryLogRecord", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.SystemLog")]
    [System.SerializableAttribute()]
    public partial class QueryLogRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueryString {
            get {
                return this.QueryStringField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryStringField, value) != true)) {
                    this.QueryStringField = value;
                    this.RaisePropertyChanged("QueryString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SJ {
            get {
                return this.SJField;
            }
            set {
                if ((this.SJField.Equals(value) != true)) {
                    this.SJField = value;
                    this.RaisePropertyChanged("SJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RefCodeTablePropertie", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.RefCode")]
    [System.SerializableAttribute()]
    public partial class RefCodeTablePropertie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeFieldNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SinoSysWatchService.Application.SinoSZJSCommonService.RefCodeType CodeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HideCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LevelDownloadModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LevelFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PyztFieldNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RefTableModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SupportLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SupportPyztField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueFieldNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeFieldName {
            get {
                return this.CodeFieldNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeFieldNameField, value) != true)) {
                    this.CodeFieldNameField = value;
                    this.RaisePropertyChanged("CodeFieldName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SinoSysWatchService.Application.SinoSZJSCommonService.RefCodeType CodeType {
            get {
                return this.CodeTypeField;
            }
            set {
                if ((this.CodeTypeField.Equals(value) != true)) {
                    this.CodeTypeField = value;
                    this.RaisePropertyChanged("CodeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayTitle {
            get {
                return this.DisplayTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayTitleField, value) != true)) {
                    this.DisplayTitleField = value;
                    this.RaisePropertyChanged("DisplayTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HideCode {
            get {
                return this.HideCodeField;
            }
            set {
                if ((this.HideCodeField.Equals(value) != true)) {
                    this.HideCodeField = value;
                    this.RaisePropertyChanged("HideCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LevelDownloadMode {
            get {
                return this.LevelDownloadModeField;
            }
            set {
                if ((this.LevelDownloadModeField.Equals(value) != true)) {
                    this.LevelDownloadModeField = value;
                    this.RaisePropertyChanged("LevelDownloadMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LevelFormat {
            get {
                return this.LevelFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.LevelFormatField, value) != true)) {
                    this.LevelFormatField = value;
                    this.RaisePropertyChanged("LevelFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PyztFieldName {
            get {
                return this.PyztFieldNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PyztFieldNameField, value) != true)) {
                    this.PyztFieldNameField = value;
                    this.RaisePropertyChanged("PyztFieldName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RefTableMode {
            get {
                return this.RefTableModeField;
            }
            set {
                if ((this.RefTableModeField.Equals(value) != true)) {
                    this.RefTableModeField = value;
                    this.RaisePropertyChanged("RefTableMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SupportLevel {
            get {
                return this.SupportLevelField;
            }
            set {
                if ((this.SupportLevelField.Equals(value) != true)) {
                    this.SupportLevelField = value;
                    this.RaisePropertyChanged("SupportLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SupportPyzt {
            get {
                return this.SupportPyztField;
            }
            set {
                if ((this.SupportPyztField.Equals(value) != true)) {
                    this.SupportPyztField = value;
                    this.RaisePropertyChanged("SupportPyzt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValueFieldName {
            get {
                return this.ValueFieldNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueFieldNameField, value) != true)) {
                    this.ValueFieldNameField = value;
                    this.RaisePropertyChanged("ValueFieldName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RefCodeType", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.RefCode")]
    public enum RefCodeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Number = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Alpha = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlphaNumber = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RefCodeData", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.RefCode", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class RefCodeData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanInputField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanShowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SinoSysWatchService.Application.SinoSZJSCommonService.RefCodeData[] ChildDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FatherCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HaveChildsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEffectiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLeavesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PYZTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanInput {
            get {
                return this.CanInputField;
            }
            set {
                if ((this.CanInputField.Equals(value) != true)) {
                    this.CanInputField = value;
                    this.RaisePropertyChanged("CanInput");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanShow {
            get {
                return this.CanShowField;
            }
            set {
                if ((this.CanShowField.Equals(value) != true)) {
                    this.CanShowField = value;
                    this.RaisePropertyChanged("CanShow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SinoSysWatchService.Application.SinoSZJSCommonService.RefCodeData[] ChildData {
            get {
                return this.ChildDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildDataField, value) != true)) {
                    this.ChildDataField = value;
                    this.RaisePropertyChanged("ChildData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayTitle {
            get {
                return this.DisplayTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayTitleField, value) != true)) {
                    this.DisplayTitleField = value;
                    this.RaisePropertyChanged("DisplayTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FatherCode {
            get {
                return this.FatherCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FatherCodeField, value) != true)) {
                    this.FatherCodeField = value;
                    this.RaisePropertyChanged("FatherCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HaveChilds {
            get {
                return this.HaveChildsField;
            }
            set {
                if ((this.HaveChildsField.Equals(value) != true)) {
                    this.HaveChildsField = value;
                    this.RaisePropertyChanged("HaveChilds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEffective {
            get {
                return this.IsEffectiveField;
            }
            set {
                if ((this.IsEffectiveField.Equals(value) != true)) {
                    this.IsEffectiveField = value;
                    this.RaisePropertyChanged("IsEffective");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLeaves {
            get {
                return this.IsLeavesField;
            }
            set {
                if ((this.IsLeavesField.Equals(value) != true)) {
                    this.IsLeavesField = value;
                    this.RaisePropertyChanged("IsLeaves");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Order {
            get {
                return this.OrderField;
            }
            set {
                if ((this.OrderField.Equals(value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PYZT {
            get {
                return this.PYZTField;
            }
            set {
                if ((object.ReferenceEquals(this.PYZTField, value) != true)) {
                    this.PYZTField = value;
                    this.RaisePropertyChanged("PYZT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WC_DataInfo", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.WorkCalendar")]
    [System.SerializableAttribute()]
    public partial class WC_DataInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime GZ_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFXSBRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTJSBRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsWorkDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Day {
            get {
                return this.DayField;
            }
            set {
                if ((this.DayField.Equals(value) != true)) {
                    this.DayField = value;
                    this.RaisePropertyChanged("Day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GZ_Date {
            get {
                return this.GZ_DateField;
            }
            set {
                if ((this.GZ_DateField.Equals(value) != true)) {
                    this.GZ_DateField = value;
                    this.RaisePropertyChanged("GZ_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFXSBR {
            get {
                return this.IsFXSBRField;
            }
            set {
                if ((this.IsFXSBRField.Equals(value) != true)) {
                    this.IsFXSBRField = value;
                    this.RaisePropertyChanged("IsFXSBR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTJSBR {
            get {
                return this.IsTJSBRField;
            }
            set {
                if ((this.IsTJSBRField.Equals(value) != true)) {
                    this.IsTJSBRField = value;
                    this.RaisePropertyChanged("IsTJSBR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsWorkDay {
            get {
                return this.IsWorkDayField;
            }
            set {
                if ((this.IsWorkDayField.Equals(value) != true)) {
                    this.IsWorkDayField = value;
                    this.RaisePropertyChanged("IsWorkDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Meta {
            get {
                return this.MetaField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaField, value) != true)) {
                    this.MetaField = value;
                    this.RaisePropertyChanged("Meta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Month {
            get {
                return this.MonthField;
            }
            set {
                if ((this.MonthField.Equals(value) != true)) {
                    this.MonthField = value;
                    this.RaisePropertyChanged("Month");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WC_TJSB_Settings", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.WorkCalendar")]
    [System.SerializableAttribute()]
    public partial class WC_TJSB_Settings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Backup_PathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FTP_AddrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FTP_PassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FTP_PathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FTP_PortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FTP_UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SBDayField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Backup_Path {
            get {
                return this.Backup_PathField;
            }
            set {
                if ((object.ReferenceEquals(this.Backup_PathField, value) != true)) {
                    this.Backup_PathField = value;
                    this.RaisePropertyChanged("Backup_Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FTP_Addr {
            get {
                return this.FTP_AddrField;
            }
            set {
                if ((object.ReferenceEquals(this.FTP_AddrField, value) != true)) {
                    this.FTP_AddrField = value;
                    this.RaisePropertyChanged("FTP_Addr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FTP_Pass {
            get {
                return this.FTP_PassField;
            }
            set {
                if ((object.ReferenceEquals(this.FTP_PassField, value) != true)) {
                    this.FTP_PassField = value;
                    this.RaisePropertyChanged("FTP_Pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FTP_Path {
            get {
                return this.FTP_PathField;
            }
            set {
                if ((object.ReferenceEquals(this.FTP_PathField, value) != true)) {
                    this.FTP_PathField = value;
                    this.RaisePropertyChanged("FTP_Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FTP_Port {
            get {
                return this.FTP_PortField;
            }
            set {
                if ((this.FTP_PortField.Equals(value) != true)) {
                    this.FTP_PortField = value;
                    this.RaisePropertyChanged("FTP_Port");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FTP_User {
            get {
                return this.FTP_UserField;
            }
            set {
                if ((object.ReferenceEquals(this.FTP_UserField, value) != true)) {
                    this.FTP_UserField = value;
                    this.RaisePropertyChanged("FTP_User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SBDay {
            get {
                return this.SBDayField;
            }
            set {
                if ((this.SBDayField.Equals(value) != true)) {
                    this.SBDayField = value;
                    this.RaisePropertyChanged("SBDay");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SinoSZJSCommonService.ICommonService")]
    public interface ICommonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetRootDwList", ReplyAction="http://tempuri.org/ICommonService/GetRootDwListResponse")]
        SinoSysWatchService.Application.SinoSZJSCommonService.SinoOrganize[] GetRootDwList(string RootDWID, decimal LevelNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetRootDwListEx", ReplyAction="http://tempuri.org/ICommonService/GetRootDwListExResponse")]
        SinoSysWatchService.Application.SinoSZJSCommonService.SinoOrganize[] GetRootDwListEx(string RootDWID, decimal LevelNum, string OrgType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetServerConfig", ReplyAction="http://tempuri.org/ICommonService/GetServerConfigResponse")]
        SinoSysWatchService.Application.SinoSZJSCommonService.ServerConfig GetServerConfig();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetDWIDByDWDM", ReplyAction="http://tempuri.org/ICommonService/GetDWIDByDWDMResponse")]
        decimal GetDWIDByDWDM(string _dwdm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/WriteExportLog", ReplyAction="http://tempuri.org/ICommonService/WriteExportLogResponse")]
        void WriteExportLog(int ExportRowCount, string ExportDataMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/WriteClientUserLog", ReplyAction="http://tempuri.org/ICommonService/WriteClientUserLogResponse")]
        void WriteClientUserLog(string Message, string LogType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetAllMenus", ReplyAction="http://tempuri.org/ICommonService/GetAllMenusResponse")]
        SinoSysWatchService.Application.SinoSZJSCommonService.SinoMenuItem[] GetAllMenus(string PostID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetfirstPage", ReplyAction="http://tempuri.org/ICommonService/GetfirstPageResponse")]
        SinoSysWatchService.Application.SinoSZJSCommonService.firstPageItem[] GetfirstPage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/WriteUserLog", ReplyAction="http://tempuri.org/ICommonService/WriteUserLogResponse")]
        bool WriteUserLog(decimal YHID, string CZLX, string CXNR, decimal ResultType, string IpAddr, string HostName, string SystemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetUserLog", ReplyAction="http://tempuri.org/ICommonService/GetUserLogResponse")]
        SinoSysWatchService.Application.SinoSZJSCommonService.UserLogRecord[] GetUserLog(System.DateTime StartDate, System.DateTime EndDate, string UserName, string Context);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetSystemLog", ReplyAction="http://tempuri.org/ICommonService/GetSystemLogResponse")]
        SinoSysWatchService.Application.SinoSZJSCommonService.SystemLogRecord[] GetSystemLog(System.DateTime StartDate, System.DateTime EndDate, string LogType, string Context);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetNotifyList", ReplyAction="http://tempuri.org/ICommonService/GetNotifyListResponse")]
        System.Data.DataTable GetNotifyList(int _num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetNotifyInfo", ReplyAction="http://tempuri.org/ICommonService/GetNotifyInfoResponse")]
        SinoSysWatchService.Application.SinoSZJSCommonService.NotifyInfo GetNotifyInfo(string _msgid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/SaveNotifyInfo", ReplyAction="http://tempuri.org/ICommonService/SaveNotifyInfoResponse")]
        bool SaveNotifyInfo(SinoSysWatchService.Application.SinoSZJSCommonService.NotifyInfo _info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/DeleteNotifyInfo", ReplyAction="http://tempuri.org/ICommonService/DeleteNotifyInfoResponse")]
        bool DeleteNotifyInfo(SinoSysWatchService.Application.SinoSZJSCommonService.NotifyInfo CurrentInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetOrgExtRootData", ReplyAction="http://tempuri.org/ICommonService/GetOrgExtRootDataResponse")]
        SinoSysWatchService.Application.SinoSZJSCommonService.OrgExtInfo[] GetOrgExtRootData(SinoSysWatchService.Application.SinoSZJSCommonService.OrgExtFieldDefine[] PropertieDefines);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetOrgExtChildData", ReplyAction="http://tempuri.org/ICommonService/GetOrgExtChildDataResponse")]
        SinoSysWatchService.Application.SinoSZJSCommonService.OrgExtInfo[] GetOrgExtChildData(string _fid, SinoSysWatchService.Application.SinoSZJSCommonService.OrgExtFieldDefine[] PropertieDefines);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/SaveOrgExtList", ReplyAction="http://tempuri.org/ICommonService/SaveOrgExtListResponse")]
        bool SaveOrgExtList(SinoSysWatchService.Application.SinoSZJSCommonService.OrgExtInfo[] BeSavedDataList, SinoSysWatchService.Application.SinoSZJSCommonService.OrgExtFieldDefine[] PropertieDefines);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetTaskInfo", ReplyAction="http://tempuri.org/ICommonService/GetTaskInfoResponse")]
        SinoSysWatchService.Application.SinoSZJSCommonService.SinoTaskInfo GetTaskInfo(string TaskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetTaskLog", ReplyAction="http://tempuri.org/ICommonService/GetTaskLogResponse")]
        System.Data.DataTable GetTaskLog(string TaskID, System.DateTime LastTime, bool GetStartData, bool OnlyErrorData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/SetTaskState", ReplyAction="http://tempuri.org/ICommonService/SetTaskStateResponse")]
        string SetTaskState(string TaskID, int NewState, int LimitState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/ResetTaskParam", ReplyAction="http://tempuri.org/ICommonService/ResetTaskParamResponse")]
        string ResetTaskParam(string TaskID, System.DateTime NextTime, string NewParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetQueryLog", ReplyAction="http://tempuri.org/ICommonService/GetQueryLogResponse")]
        SinoSysWatchService.Application.SinoSZJSCommonService.QueryLogRecord[] GetQueryLog(System.DateTime _startDate, System.DateTime _endDate, string _userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetRefCodePropertie", ReplyAction="http://tempuri.org/ICommonService/GetRefCodePropertieResponse")]
        SinoSysWatchService.Application.SinoSZJSCommonService.RefCodeTablePropertie GetRefCodePropertie(string _refCodeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetFullRefCodeData", ReplyAction="http://tempuri.org/ICommonService/GetFullRefCodeDataResponse")]
        SinoSysWatchService.Application.SinoSZJSCommonService.RefCodeData[] GetFullRefCodeData(string _refCodeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetChildRefCodeData", ReplyAction="http://tempuri.org/ICommonService/GetChildRefCodeDataResponse")]
        SinoSysWatchService.Application.SinoSZJSCommonService.RefCodeData[] GetChildRefCodeData(string _refCodeName, string _fatherCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetRefCodeByCode", ReplyAction="http://tempuri.org/ICommonService/GetRefCodeByCodeResponse")]
        SinoSysWatchService.Application.SinoSZJSCommonService.RefCodeData GetRefCodeByCode(string _refCodeName, string _value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetDataInfo", ReplyAction="http://tempuri.org/ICommonService/GetDataInfoResponse")]
        SinoSysWatchService.Application.SinoSZJSCommonService.WC_DataInfo[] GetDataInfo(int Year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/SaveDataInfo", ReplyAction="http://tempuri.org/ICommonService/SaveDataInfoResponse")]
        bool SaveDataInfo(SinoSysWatchService.Application.SinoSZJSCommonService.WC_DataInfo DataInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetTJSBSettings", ReplyAction="http://tempuri.org/ICommonService/GetTJSBSettingsResponse")]
        SinoSysWatchService.Application.SinoSZJSCommonService.WC_TJSB_Settings GetTJSBSettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/SaveTJSBSettings", ReplyAction="http://tempuri.org/ICommonService/SaveTJSBSettingsResponse")]
        bool SaveTJSBSettings(SinoSysWatchService.Application.SinoSZJSCommonService.WC_TJSB_Settings Settings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/ResetService", ReplyAction="http://tempuri.org/ICommonService/ResetServiceResponse")]
        bool ResetService(string ServiceName, string state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetServiceState", ReplyAction="http://tempuri.org/ICommonService/GetServiceStateResponse")]
        string GetServiceState(string ServiceName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/RecycleIISPool", ReplyAction="http://tempuri.org/ICommonService/RecycleIISPoolResponse")]
        string RecycleIISPool(string AppPoolName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/HeartBeat", ReplyAction="http://tempuri.org/ICommonService/HeartBeatResponse")]
        bool HeartBeat();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommonServiceChannel : SinoSysWatchService.Application.SinoSZJSCommonService.ICommonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommonServiceClient : System.ServiceModel.ClientBase<SinoSysWatchService.Application.SinoSZJSCommonService.ICommonService>, SinoSysWatchService.Application.SinoSZJSCommonService.ICommonService {
        
        public CommonServiceClient() {
        }
        
        public CommonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SinoSysWatchService.Application.SinoSZJSCommonService.SinoOrganize[] GetRootDwList(string RootDWID, decimal LevelNum) {
            return base.Channel.GetRootDwList(RootDWID, LevelNum);
        }
        
        public SinoSysWatchService.Application.SinoSZJSCommonService.SinoOrganize[] GetRootDwListEx(string RootDWID, decimal LevelNum, string OrgType) {
            return base.Channel.GetRootDwListEx(RootDWID, LevelNum, OrgType);
        }
        
        public SinoSysWatchService.Application.SinoSZJSCommonService.ServerConfig GetServerConfig() {
            return base.Channel.GetServerConfig();
        }
        
        public decimal GetDWIDByDWDM(string _dwdm) {
            return base.Channel.GetDWIDByDWDM(_dwdm);
        }
        
        public void WriteExportLog(int ExportRowCount, string ExportDataMsg) {
            base.Channel.WriteExportLog(ExportRowCount, ExportDataMsg);
        }
        
        public void WriteClientUserLog(string Message, string LogType) {
            base.Channel.WriteClientUserLog(Message, LogType);
        }
        
        public SinoSysWatchService.Application.SinoSZJSCommonService.SinoMenuItem[] GetAllMenus(string PostID) {
            return base.Channel.GetAllMenus(PostID);
        }
        
        public SinoSysWatchService.Application.SinoSZJSCommonService.firstPageItem[] GetfirstPage() {
            return base.Channel.GetfirstPage();
        }
        
        public bool WriteUserLog(decimal YHID, string CZLX, string CXNR, decimal ResultType, string IpAddr, string HostName, string SystemID) {
            return base.Channel.WriteUserLog(YHID, CZLX, CXNR, ResultType, IpAddr, HostName, SystemID);
        }
        
        public SinoSysWatchService.Application.SinoSZJSCommonService.UserLogRecord[] GetUserLog(System.DateTime StartDate, System.DateTime EndDate, string UserName, string Context) {
            return base.Channel.GetUserLog(StartDate, EndDate, UserName, Context);
        }
        
        public SinoSysWatchService.Application.SinoSZJSCommonService.SystemLogRecord[] GetSystemLog(System.DateTime StartDate, System.DateTime EndDate, string LogType, string Context) {
            return base.Channel.GetSystemLog(StartDate, EndDate, LogType, Context);
        }
        
        public System.Data.DataTable GetNotifyList(int _num) {
            return base.Channel.GetNotifyList(_num);
        }
        
        public SinoSysWatchService.Application.SinoSZJSCommonService.NotifyInfo GetNotifyInfo(string _msgid) {
            return base.Channel.GetNotifyInfo(_msgid);
        }
        
        public bool SaveNotifyInfo(SinoSysWatchService.Application.SinoSZJSCommonService.NotifyInfo _info) {
            return base.Channel.SaveNotifyInfo(_info);
        }
        
        public bool DeleteNotifyInfo(SinoSysWatchService.Application.SinoSZJSCommonService.NotifyInfo CurrentInfo) {
            return base.Channel.DeleteNotifyInfo(CurrentInfo);
        }
        
        public SinoSysWatchService.Application.SinoSZJSCommonService.OrgExtInfo[] GetOrgExtRootData(SinoSysWatchService.Application.SinoSZJSCommonService.OrgExtFieldDefine[] PropertieDefines) {
            return base.Channel.GetOrgExtRootData(PropertieDefines);
        }
        
        public SinoSysWatchService.Application.SinoSZJSCommonService.OrgExtInfo[] GetOrgExtChildData(string _fid, SinoSysWatchService.Application.SinoSZJSCommonService.OrgExtFieldDefine[] PropertieDefines) {
            return base.Channel.GetOrgExtChildData(_fid, PropertieDefines);
        }
        
        public bool SaveOrgExtList(SinoSysWatchService.Application.SinoSZJSCommonService.OrgExtInfo[] BeSavedDataList, SinoSysWatchService.Application.SinoSZJSCommonService.OrgExtFieldDefine[] PropertieDefines) {
            return base.Channel.SaveOrgExtList(BeSavedDataList, PropertieDefines);
        }
        
        public SinoSysWatchService.Application.SinoSZJSCommonService.SinoTaskInfo GetTaskInfo(string TaskID) {
            return base.Channel.GetTaskInfo(TaskID);
        }
        
        public System.Data.DataTable GetTaskLog(string TaskID, System.DateTime LastTime, bool GetStartData, bool OnlyErrorData) {
            return base.Channel.GetTaskLog(TaskID, LastTime, GetStartData, OnlyErrorData);
        }
        
        public string SetTaskState(string TaskID, int NewState, int LimitState) {
            return base.Channel.SetTaskState(TaskID, NewState, LimitState);
        }
        
        public string ResetTaskParam(string TaskID, System.DateTime NextTime, string NewParam) {
            return base.Channel.ResetTaskParam(TaskID, NextTime, NewParam);
        }
        
        public SinoSysWatchService.Application.SinoSZJSCommonService.QueryLogRecord[] GetQueryLog(System.DateTime _startDate, System.DateTime _endDate, string _userName) {
            return base.Channel.GetQueryLog(_startDate, _endDate, _userName);
        }
        
        public SinoSysWatchService.Application.SinoSZJSCommonService.RefCodeTablePropertie GetRefCodePropertie(string _refCodeName) {
            return base.Channel.GetRefCodePropertie(_refCodeName);
        }
        
        public SinoSysWatchService.Application.SinoSZJSCommonService.RefCodeData[] GetFullRefCodeData(string _refCodeName) {
            return base.Channel.GetFullRefCodeData(_refCodeName);
        }
        
        public SinoSysWatchService.Application.SinoSZJSCommonService.RefCodeData[] GetChildRefCodeData(string _refCodeName, string _fatherCode) {
            return base.Channel.GetChildRefCodeData(_refCodeName, _fatherCode);
        }
        
        public SinoSysWatchService.Application.SinoSZJSCommonService.RefCodeData GetRefCodeByCode(string _refCodeName, string _value) {
            return base.Channel.GetRefCodeByCode(_refCodeName, _value);
        }
        
        public SinoSysWatchService.Application.SinoSZJSCommonService.WC_DataInfo[] GetDataInfo(int Year) {
            return base.Channel.GetDataInfo(Year);
        }
        
        public bool SaveDataInfo(SinoSysWatchService.Application.SinoSZJSCommonService.WC_DataInfo DataInfo) {
            return base.Channel.SaveDataInfo(DataInfo);
        }
        
        public SinoSysWatchService.Application.SinoSZJSCommonService.WC_TJSB_Settings GetTJSBSettings() {
            return base.Channel.GetTJSBSettings();
        }
        
        public bool SaveTJSBSettings(SinoSysWatchService.Application.SinoSZJSCommonService.WC_TJSB_Settings Settings) {
            return base.Channel.SaveTJSBSettings(Settings);
        }
        
        public bool ResetService(string ServiceName, string state) {
            return base.Channel.ResetService(ServiceName, state);
        }
        
        public string GetServiceState(string ServiceName) {
            return base.Channel.GetServiceState(ServiceName);
        }
        
        public string RecycleIISPool(string AppPoolName) {
            return base.Channel.RecycleIISPool(AppPoolName);
        }
        
        public bool HeartBeat() {
            return base.Channel.HeartBeat();
        }
    }
}
