//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinoSysMonitorCenter.SysWatchService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SysWatchService.ISWCommandService")]
    public interface ISWCommandService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWCommandService/DoCommand", ReplyAction="http://tempuri.org/ISWCommandService/DoCommandResponse")]
        byte[] DoCommand(string Token, string CommandName, byte[] ParameterData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISWCommandServiceChannel : SinoSysMonitorCenter.SysWatchService.ISWCommandService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SWCommandServiceClient : System.ServiceModel.ClientBase<SinoSysMonitorCenter.SysWatchService.ISWCommandService>, SinoSysMonitorCenter.SysWatchService.ISWCommandService {
        
        public SWCommandServiceClient() {
        }
        
        public SWCommandServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SWCommandServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWCommandServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWCommandServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] DoCommand(string Token, string CommandName, byte[] ParameterData) {
            return base.Channel.DoCommand(Token, CommandName, ParameterData);
        }
    }
}
