//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines
{
    using System;
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="ViewCategory", Namespace="http://schemas.datacontract.org/2004/07/ChinaCustoms.Frameworks.Cupaa.Libraries.C" +
        "ore.EnumsDefines")]
    public enum ViewCategory : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ViewCode = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ViewGuid = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationCategory", Namespace="http://schemas.datacontract.org/2004/07/ChinaCustoms.Frameworks.Cupaa.Libraries.C" +
        "ore.EnumsDefines")]
    public enum OrganizationCategory : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrgGuid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrgOriginalSort = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrgAllPathName = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrgGlobalSort = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrgCustomsCode = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListObjectCategories", Namespace="http://schemas.datacontract.org/2004/07/ChinaCustoms.Frameworks.Cupaa.Libraries.C" +
        "ore.EnumsDefines")]
    public enum ListObjectCategories : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Organizations = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Users = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Groups = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sideline = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 65535,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectStatusCategories", Namespace="http://schemas.datacontract.org/2004/07/ChinaCustoms.Frameworks.Cupaa.Libraries.C" +
        "ore.EnumsDefines")]
    public enum ObjectStatusCategories : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Common = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DirectLogic = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConjunctOrgLogic = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConjunctUserLogic = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 65535,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectCategory", Namespace="http://schemas.datacontract.org/2004/07/ChinaCustoms.Frameworks.Cupaa.Libraries.C" +
        "ore.EnumsDefines")]
    public enum ObjectCategory : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrgGuid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrgOriginalSort = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrgAllPathName = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrgGlobalSort = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrgCustomsCode = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserGuid = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserOriginalSort = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserAllPathName = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserGlobalSort = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserIdentity = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GroupGuid = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GroupOriginalSort = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GroupAllPathName = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GroupGlobalSort = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Guid = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OriginalSort = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AllPathName = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GlobalSort = 18,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserCategory", Namespace="http://schemas.datacontract.org/2004/07/ChinaCustoms.Frameworks.Cupaa.Libraries.C" +
        "ore.EnumsDefines")]
    public enum UserCategory : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserGuid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserOriginalSort = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserAllPathName = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserGlobalSort = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserIdentity = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupCategory", Namespace="http://schemas.datacontract.org/2004/07/ChinaCustoms.Frameworks.Cupaa.Libraries.C" +
        "ore.EnumsDefines")]
    public enum GroupCategory : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GroupGuid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GroupOriginalSort = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GroupAllPathName = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GroupGlobalSort = 4,
    }
}
namespace ChinaCustoms.Frameworks.Cupaa.Libraries.Core.Common.Log
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CupaaFaultArgs", Namespace="http://schemas.datacontract.org/2004/07/ChinaCustoms.Frameworks.Cupaa.Libraries.C" +
        "ore.Common.Log")]
    public partial class CupaaFaultArgs : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IDField;
        
        private string InnerExceptionMessageField;
        
        private string InnerStackTraceField;
        
        private string MessageField;
        
        private int NumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InnerExceptionMessage
        {
            get
            {
                return this.InnerExceptionMessageField;
            }
            set
            {
                this.InnerExceptionMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InnerStackTrace
        {
            get
            {
                return this.InnerStackTraceField;
            }
            set
            {
                this.InnerStackTraceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://h2010.customs.gov.cn/Cupaa/Contracts", ConfigurationName="IOguReader")]
public interface IOguReader
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetOuView", ReplyAction="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetOuViewResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ChinaCustoms.Frameworks.Cupaa.Libraries.Core.Common.Log.CupaaFaultArgs), Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetOuViewCupaaFaultArgsFau" +
        "lt", Name="CupaaFaultArgs", Namespace="http://schemas.datacontract.org/2004/07/ChinaCustoms.Frameworks.Cupaa.Libraries.C" +
        "ore.Common.Log")]
    System.Xml.XmlElement GetOuView(string viewValues, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ViewCategory viewCategory);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetRootDepartment", ReplyAction="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetRootDepartmentResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ChinaCustoms.Frameworks.Cupaa.Libraries.Core.Common.Log.CupaaFaultArgs), Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetRootDepartmentCupaaFaul" +
        "tArgsFault", Name="CupaaFaultArgs", Namespace="http://schemas.datacontract.org/2004/07/ChinaCustoms.Frameworks.Cupaa.Libraries.C" +
        "ore.Common.Log")]
    System.Xml.XmlElement GetRootDepartment(string viewValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ViewCategory viewCategory, string extraAttributes);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetOrganizationChildren", ReplyAction="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetOrganizationChildrenRes" +
        "ponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ChinaCustoms.Frameworks.Cupaa.Libraries.Core.Common.Log.CupaaFaultArgs), Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetOrganizationChildrenCup" +
        "aaFaultArgsFault", Name="CupaaFaultArgs", Namespace="http://schemas.datacontract.org/2004/07/ChinaCustoms.Frameworks.Cupaa.Libraries.C" +
        "ore.Common.Log")]
    System.Xml.XmlElement GetOrganizationChildren(string viewValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ViewCategory viewCategory, string orgValues, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.OrganizationCategory orgCategory, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ListObjectCategories listObjCategories, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ObjectStatusCategories objectStatusCategories, int orgDepth, string orgRank, string userRank, string orgType, int orgClass, string extraAttributes);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetObjectsDetail", ReplyAction="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetObjectsDetailResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ChinaCustoms.Frameworks.Cupaa.Libraries.Core.Common.Log.CupaaFaultArgs), Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetObjectsDetailCupaaFault" +
        "ArgsFault", Name="CupaaFaultArgs", Namespace="http://schemas.datacontract.org/2004/07/ChinaCustoms.Frameworks.Cupaa.Libraries.C" +
        "ore.Common.Log")]
    System.Xml.XmlElement GetObjectsDetail(string viewValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ViewCategory viewCategory, string objValues, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ObjectCategory objectCategory, string parentOrgValues, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.OrganizationCategory parentOrgCategory, string extraAttributes);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetObjectParentOrganizatio" +
        "ns", ReplyAction="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetObjectParentOrganizatio" +
        "nsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ChinaCustoms.Frameworks.Cupaa.Libraries.Core.Common.Log.CupaaFaultArgs), Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetObjectParentOrganizatio" +
        "nsCupaaFaultArgsFault", Name="CupaaFaultArgs", Namespace="http://schemas.datacontract.org/2004/07/ChinaCustoms.Frameworks.Cupaa.Libraries.C" +
        "ore.Common.Log")]
    System.Xml.XmlElement GetObjectParentOrganizations(string viewValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ViewCategory viewCategory, string objValues, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ObjectCategory objectCategory, string parentValues, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.OrganizationCategory organizationCategory, bool onlyDirectlyOrgs, bool isWithVisualOrgs, string orgRank, string extraAttributes);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetUserIdentityInfos", ReplyAction="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetUserIdentityInfosRespon" +
        "se")]
    [System.ServiceModel.FaultContractAttribute(typeof(ChinaCustoms.Frameworks.Cupaa.Libraries.Core.Common.Log.CupaaFaultArgs), Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetUserIdentityInfosCupaaF" +
        "aultArgsFault", Name="CupaaFaultArgs", Namespace="http://schemas.datacontract.org/2004/07/ChinaCustoms.Frameworks.Cupaa.Libraries.C" +
        "ore.Common.Log")]
    System.Xml.XmlElement GetUserIdentityInfos(string userValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.UserCategory userCategory);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/CheckPwd", ReplyAction="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/CheckPwdResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ChinaCustoms.Frameworks.Cupaa.Libraries.Core.Common.Log.CupaaFaultArgs), Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/CheckPwdCupaaFaultArgsFaul" +
        "t", Name="CupaaFaultArgs", Namespace="http://schemas.datacontract.org/2004/07/ChinaCustoms.Frameworks.Cupaa.Libraries.C" +
        "ore.Common.Log")]
    bool CheckPwd(string identityName, string identityType, string userPwd);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetViewInfosByUser", ReplyAction="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetViewInfosByUserResponse" +
        "")]
    [System.ServiceModel.FaultContractAttribute(typeof(ChinaCustoms.Frameworks.Cupaa.Libraries.Core.Common.Log.CupaaFaultArgs), Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetViewInfosByUserCupaaFau" +
        "ltArgsFault", Name="CupaaFaultArgs", Namespace="http://schemas.datacontract.org/2004/07/ChinaCustoms.Frameworks.Cupaa.Libraries.C" +
        "ore.Common.Log")]
    System.Xml.XmlElement GetViewInfosByUser(string userValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.UserCategory userCategory, bool isIncludeDisabledViews);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetGroupsOfUsers", ReplyAction="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetGroupsOfUsersResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ChinaCustoms.Frameworks.Cupaa.Libraries.Core.Common.Log.CupaaFaultArgs), Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetGroupsOfUsersCupaaFault" +
        "ArgsFault", Name="CupaaFaultArgs", Namespace="http://schemas.datacontract.org/2004/07/ChinaCustoms.Frameworks.Cupaa.Libraries.C" +
        "ore.Common.Log")]
    System.Xml.XmlElement GetGroupsOfUsers(string viewValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ViewCategory viewCategory, string userValues, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.UserCategory userCategory, string parentOrgValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.OrganizationCategory parentOrgCategory, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ObjectStatusCategories objectStatusCategories, string extraAttributes);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetUsersInGroups", ReplyAction="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetUsersInGroupsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ChinaCustoms.Frameworks.Cupaa.Libraries.Core.Common.Log.CupaaFaultArgs), Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetUsersInGroupsCupaaFault" +
        "ArgsFault", Name="CupaaFaultArgs", Namespace="http://schemas.datacontract.org/2004/07/ChinaCustoms.Frameworks.Cupaa.Libraries.C" +
        "ore.Common.Log")]
    System.Xml.XmlElement GetUsersInGroups(string viewValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ViewCategory viewCategory, string groupValues, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.GroupCategory groupCategory, string userRank, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ObjectStatusCategories objectStatusCategories, string extraAttributes);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/QueryOguByCondition", ReplyAction="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/QueryOguByConditionRespons" +
        "e")]
    [System.ServiceModel.FaultContractAttribute(typeof(ChinaCustoms.Frameworks.Cupaa.Libraries.Core.Common.Log.CupaaFaultArgs), Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/QueryOguByConditionCupaaFa" +
        "ultArgsFault", Name="CupaaFaultArgs", Namespace="http://schemas.datacontract.org/2004/07/ChinaCustoms.Frameworks.Cupaa.Libraries.C" +
        "ore.Common.Log")]
    System.Xml.XmlElement QueryOguByCondition(string viewValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ViewCategory viewCategory, string orgValues, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.OrganizationCategory orgCategory, string objValue, bool isFuzzy, bool isFirstPerson, string orgRank, string userRank, int depth, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ListObjectCategories listObjCategories, string extraAttributes);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetDirectCustoms", ReplyAction="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetDirectCustomsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ChinaCustoms.Frameworks.Cupaa.Libraries.Core.Common.Log.CupaaFaultArgs), Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetDirectCustomsCupaaFault" +
        "ArgsFault", Name="CupaaFaultArgs", Namespace="http://schemas.datacontract.org/2004/07/ChinaCustoms.Frameworks.Cupaa.Libraries.C" +
        "ore.Common.Log")]
    System.Xml.XmlElement GetDirectCustoms(string viewValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ViewCategory viewCategory, string objValues, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ObjectCategory objCategory, string parentOrgValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.OrganizationCategory parentOrgCategory, string extraAttributes);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetSubjectCustoms", ReplyAction="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetSubjectCustomsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ChinaCustoms.Frameworks.Cupaa.Libraries.Core.Common.Log.CupaaFaultArgs), Action="http://h2010.customs.gov.cn/Cupaa/Contracts/IOguReader/GetSubjectCustomsCupaaFaul" +
        "tArgsFault", Name="CupaaFaultArgs", Namespace="http://schemas.datacontract.org/2004/07/ChinaCustoms.Frameworks.Cupaa.Libraries.C" +
        "ore.Common.Log")]
    System.Xml.XmlElement GetSubjectCustoms(string viewValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ViewCategory viewCategory, string objValues, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ObjectCategory objCategory, string parentOrgValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.OrganizationCategory parentOrgCategory, string extraAttributes);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IOguReaderChannel : IOguReader, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class OguReaderClient : System.ServiceModel.ClientBase<IOguReader>, IOguReader
{
    
    public OguReaderClient()
    {
    }
    
    public OguReaderClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public OguReaderClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public OguReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public OguReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Xml.XmlElement GetOuView(string viewValues, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ViewCategory viewCategory)
    {
        return base.Channel.GetOuView(viewValues, viewCategory);
    }
    
    public System.Xml.XmlElement GetRootDepartment(string viewValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ViewCategory viewCategory, string extraAttributes)
    {
        return base.Channel.GetRootDepartment(viewValue, viewCategory, extraAttributes);
    }
    
    public System.Xml.XmlElement GetOrganizationChildren(string viewValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ViewCategory viewCategory, string orgValues, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.OrganizationCategory orgCategory, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ListObjectCategories listObjCategories, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ObjectStatusCategories objectStatusCategories, int orgDepth, string orgRank, string userRank, string orgType, int orgClass, string extraAttributes)
    {
        return base.Channel.GetOrganizationChildren(viewValue, viewCategory, orgValues, orgCategory, listObjCategories, objectStatusCategories, orgDepth, orgRank, userRank, orgType, orgClass, extraAttributes);
    }
    
    public System.Xml.XmlElement GetObjectsDetail(string viewValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ViewCategory viewCategory, string objValues, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ObjectCategory objectCategory, string parentOrgValues, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.OrganizationCategory parentOrgCategory, string extraAttributes)
    {
        return base.Channel.GetObjectsDetail(viewValue, viewCategory, objValues, objectCategory, parentOrgValues, parentOrgCategory, extraAttributes);
    }
    
    public System.Xml.XmlElement GetObjectParentOrganizations(string viewValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ViewCategory viewCategory, string objValues, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ObjectCategory objectCategory, string parentValues, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.OrganizationCategory organizationCategory, bool onlyDirectlyOrgs, bool isWithVisualOrgs, string orgRank, string extraAttributes)
    {
        return base.Channel.GetObjectParentOrganizations(viewValue, viewCategory, objValues, objectCategory, parentValues, organizationCategory, onlyDirectlyOrgs, isWithVisualOrgs, orgRank, extraAttributes);
    }
    
    public System.Xml.XmlElement GetUserIdentityInfos(string userValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.UserCategory userCategory)
    {
        return base.Channel.GetUserIdentityInfos(userValue, userCategory);
    }
    
    public bool CheckPwd(string identityName, string identityType, string userPwd)
    {
        return base.Channel.CheckPwd(identityName, identityType, userPwd);
    }
    
    public System.Xml.XmlElement GetViewInfosByUser(string userValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.UserCategory userCategory, bool isIncludeDisabledViews)
    {
        return base.Channel.GetViewInfosByUser(userValue, userCategory, isIncludeDisabledViews);
    }
    
    public System.Xml.XmlElement GetGroupsOfUsers(string viewValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ViewCategory viewCategory, string userValues, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.UserCategory userCategory, string parentOrgValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.OrganizationCategory parentOrgCategory, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ObjectStatusCategories objectStatusCategories, string extraAttributes)
    {
        return base.Channel.GetGroupsOfUsers(viewValue, viewCategory, userValues, userCategory, parentOrgValue, parentOrgCategory, objectStatusCategories, extraAttributes);
    }
    
    public System.Xml.XmlElement GetUsersInGroups(string viewValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ViewCategory viewCategory, string groupValues, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.GroupCategory groupCategory, string userRank, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ObjectStatusCategories objectStatusCategories, string extraAttributes)
    {
        return base.Channel.GetUsersInGroups(viewValue, viewCategory, groupValues, groupCategory, userRank, objectStatusCategories, extraAttributes);
    }
    
    public System.Xml.XmlElement QueryOguByCondition(string viewValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ViewCategory viewCategory, string orgValues, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.OrganizationCategory orgCategory, string objValue, bool isFuzzy, bool isFirstPerson, string orgRank, string userRank, int depth, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ListObjectCategories listObjCategories, string extraAttributes)
    {
        return base.Channel.QueryOguByCondition(viewValue, viewCategory, orgValues, orgCategory, objValue, isFuzzy, isFirstPerson, orgRank, userRank, depth, listObjCategories, extraAttributes);
    }
    
    public System.Xml.XmlElement GetDirectCustoms(string viewValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ViewCategory viewCategory, string objValues, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ObjectCategory objCategory, string parentOrgValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.OrganizationCategory parentOrgCategory, string extraAttributes)
    {
        return base.Channel.GetDirectCustoms(viewValue, viewCategory, objValues, objCategory, parentOrgValue, parentOrgCategory, extraAttributes);
    }
    
    public System.Xml.XmlElement GetSubjectCustoms(string viewValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ViewCategory viewCategory, string objValues, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.ObjectCategory objCategory, string parentOrgValue, ChinaCustoms.Frameworks.Cupaa.Libraries.Core.EnumsDefines.OrganizationCategory parentOrgCategory, string extraAttributes)
    {
        return base.Channel.GetSubjectCustoms(viewValue, viewCategory, objValues, objCategory, parentOrgValue, parentOrgCategory, extraAttributes);
    }
}
