//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4963
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace CustomsSZQueryProxy {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SimpleCustomsQuerySoap", Namespace="http://tempuri.org/")]
    public partial class SimpleCustomsQuery : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback QueryDataOperationCompleted;
        
        /// <remarks/>
        public SimpleCustomsQuery() {
            this.Url = "http://localhost:2235/SimpleCustomsQuery.asmx";
        }
        
        /// <remarks/>
        public event QueryDataCompletedEventHandler QueryDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable QueryData(string strSQL, string UserName) {
            object[] results = this.Invoke("QueryData", new object[] {
                        strSQL,
                        UserName});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginQueryData(string strSQL, string UserName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("QueryData", new object[] {
                        strSQL,
                        UserName}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndQueryData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void QueryDataAsync(string strSQL, string UserName) {
            this.QueryDataAsync(strSQL, UserName, null);
        }
        
        /// <remarks/>
        public void QueryDataAsync(string strSQL, string UserName, object userState) {
            if ((this.QueryDataOperationCompleted == null)) {
                this.QueryDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryDataOperationCompleted);
            }
            this.InvokeAsync("QueryData", new object[] {
                        strSQL,
                        UserName}, this.QueryDataOperationCompleted, userState);
        }
        
        private void OnQueryDataOperationCompleted(object arg) {
            if ((this.QueryDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryDataCompleted(this, new QueryDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void QueryDataCompletedEventHandler(object sender, QueryDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}
