//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinoSysWatchService.Application.SinoSZJSUserManagerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserMappingInfo", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.User")]
    [System.SerializableAttribute()]
    public partial class UserMappingInfo : SinoSysWatchService.Application.SinoSZJSUserManagerService.UserBaseInfo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TRD_LoginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TRD_XMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TRD_YHIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TRD_LoginName {
            get {
                return this.TRD_LoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TRD_LoginNameField, value) != true)) {
                    this.TRD_LoginNameField = value;
                    this.RaisePropertyChanged("TRD_LoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TRD_XM {
            get {
                return this.TRD_XMField;
            }
            set {
                if ((object.ReferenceEquals(this.TRD_XMField, value) != true)) {
                    this.TRD_XMField = value;
                    this.RaisePropertyChanged("TRD_XM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TRD_YHID {
            get {
                return this.TRD_YHIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TRD_YHIDField, value) != true)) {
                    this.TRD_YHIDField = value;
                    this.RaisePropertyChanged("TRD_YHID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserBaseInfo", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.User")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SinoSysWatchService.Application.SinoSZJSUserManagerService.UserMappingInfo))]
    public partial class UserBaseInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomsNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeadShipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgShortNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoliceNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecretField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomsNO {
            get {
                return this.CustomsNOField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomsNOField, value) != true)) {
                    this.CustomsNOField = value;
                    this.RaisePropertyChanged("CustomsNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HeadShip {
            get {
                return this.HeadShipField;
            }
            set {
                if ((object.ReferenceEquals(this.HeadShipField, value) != true)) {
                    this.HeadShipField = value;
                    this.RaisePropertyChanged("HeadShip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Level {
            get {
                return this.LevelField;
            }
            set {
                if ((object.ReferenceEquals(this.LevelField, value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Limit {
            get {
                return this.LimitField;
            }
            set {
                if ((object.ReferenceEquals(this.LimitField, value) != true)) {
                    this.LimitField = value;
                    this.RaisePropertyChanged("Limit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginName {
            get {
                return this.LoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginNameField, value) != true)) {
                    this.LoginNameField = value;
                    this.RaisePropertyChanged("LoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgFullName {
            get {
                return this.OrgFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgFullNameField, value) != true)) {
                    this.OrgFullNameField = value;
                    this.RaisePropertyChanged("OrgFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgID {
            get {
                return this.OrgIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgIDField, value) != true)) {
                    this.OrgIDField = value;
                    this.RaisePropertyChanged("OrgID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgShortName {
            get {
                return this.OrgShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgShortNameField, value) != true)) {
                    this.OrgShortNameField = value;
                    this.RaisePropertyChanged("OrgShortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonIDField, value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PoliceNO {
            get {
                return this.PoliceNOField;
            }
            set {
                if ((object.ReferenceEquals(this.PoliceNOField, value) != true)) {
                    this.PoliceNOField = value;
                    this.RaisePropertyChanged("PoliceNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Secret {
            get {
                return this.SecretField;
            }
            set {
                if ((object.ReferenceEquals(this.SecretField, value) != true)) {
                    this.SecretField = value;
                    this.RaisePropertyChanged("Secret");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserExtInfo", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.User")]
    [System.SerializableAttribute()]
    public partial class UserExtInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMAILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogonNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMAIL {
            get {
                return this.EMAILField;
            }
            set {
                if ((object.ReferenceEquals(this.EMAILField, value) != true)) {
                    this.EMAILField = value;
                    this.RaisePropertyChanged("EMAIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonName {
            get {
                return this.LogonNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LogonNameField, value) != true)) {
                    this.LogonNameField = value;
                    this.RaisePropertyChanged("LogonName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonBaseInfo", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.User")]
    [System.SerializableAttribute()]
    public partial class PersonBaseInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeadShipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgShortNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HeadShip {
            get {
                return this.HeadShipField;
            }
            set {
                if ((object.ReferenceEquals(this.HeadShipField, value) != true)) {
                    this.HeadShipField = value;
                    this.RaisePropertyChanged("HeadShip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginName {
            get {
                return this.LoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginNameField, value) != true)) {
                    this.LoginNameField = value;
                    this.RaisePropertyChanged("LoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgFullName {
            get {
                return this.OrgFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgFullNameField, value) != true)) {
                    this.OrgFullNameField = value;
                    this.RaisePropertyChanged("OrgFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgID {
            get {
                return this.OrgIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgIDField, value) != true)) {
                    this.OrgIDField = value;
                    this.RaisePropertyChanged("OrgID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgShortName {
            get {
                return this.OrgShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgShortNameField, value) != true)) {
                    this.OrgShortNameField = value;
                    this.RaisePropertyChanged("OrgShortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SinoRole", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.Authorize")]
    [System.SerializableAttribute()]
    public partial class SinoRole : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOwnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleDwidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoRightItem[] UserRightsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descript {
            get {
                return this.DescriptField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptField, value) != true)) {
                    this.DescriptField = value;
                    this.RaisePropertyChanged("Descript");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOwn {
            get {
                return this.IsOwnField;
            }
            set {
                if ((this.IsOwnField.Equals(value) != true)) {
                    this.IsOwnField = value;
                    this.RaisePropertyChanged("IsOwn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleDwid {
            get {
                return this.RoleDwidField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleDwidField, value) != true)) {
                    this.RoleDwidField = value;
                    this.RaisePropertyChanged("RoleDwid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleID {
            get {
                return this.RoleIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleIDField, value) != true)) {
                    this.RoleIDField = value;
                    this.RaisePropertyChanged("RoleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoRightItem[] UserRights {
            get {
                return this.UserRightsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserRightsField, value) != true)) {
                    this.UserRightsField = value;
                    this.RaisePropertyChanged("UserRights");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SinoRightItem", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.Authorize")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SinoSysWatchService.Application.SinoSZJSUserManagerService.UserMappingInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SinoSysWatchService.Application.SinoSZJSUserManagerService.UserMappingInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SinoSysWatchService.Application.SinoSZJSUserManagerService.UserBaseInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SinoSysWatchService.Application.SinoSZJSUserManagerService.UserBaseInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SinoSysWatchService.Application.SinoSZJSUserManagerService.UserExtInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SinoSysWatchService.Application.SinoSZJSUserManagerService.UserExtInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SinoSysWatchService.Application.SinoSZJSUserManagerService.PersonBaseInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SinoSysWatchService.Application.SinoSZJSUserManagerService.PersonBaseInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SinoSysWatchService.Application.SinoSZJSUserManagerService.UserRightInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SinoSysWatchService.Application.SinoSZJSUserManagerService.UserRightInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SinoSysWatchService.Application.SinoSZJSUserManagerService.UserQueryModelInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SinoSysWatchService.Application.SinoSZJSUserManagerService.UserQueryModelInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SinoSysWatchService.Application.SinoSZJSUserManagerService.UserPostInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SinoSysWatchService.Application.SinoSZJSUserManagerService.UserPostInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoRole[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoRole))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoRightItem[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoOrganize))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoPost[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoPost))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SinoSysWatchService.Application.SinoSZJSUserManagerService.UserRightItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, SinoSysWatchService.Application.SinoSZJSUserManagerService.UserRightItem>))]
    public partial class SinoRightItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FatherRightIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenuIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RightDescriptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RightIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] RightLevelsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RightMetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RightNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RightTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FatherRightID {
            get {
                return this.FatherRightIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FatherRightIDField, value) != true)) {
                    this.FatherRightIDField = value;
                    this.RaisePropertyChanged("FatherRightID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuID {
            get {
                return this.MenuIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuIDField, value) != true)) {
                    this.MenuIDField = value;
                    this.RaisePropertyChanged("MenuID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RightDescript {
            get {
                return this.RightDescriptField;
            }
            set {
                if ((object.ReferenceEquals(this.RightDescriptField, value) != true)) {
                    this.RightDescriptField = value;
                    this.RaisePropertyChanged("RightDescript");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RightID {
            get {
                return this.RightIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RightIDField, value) != true)) {
                    this.RightIDField = value;
                    this.RaisePropertyChanged("RightID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] RightLevels {
            get {
                return this.RightLevelsField;
            }
            set {
                if ((object.ReferenceEquals(this.RightLevelsField, value) != true)) {
                    this.RightLevelsField = value;
                    this.RaisePropertyChanged("RightLevels");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RightMeta {
            get {
                return this.RightMetaField;
            }
            set {
                if ((object.ReferenceEquals(this.RightMetaField, value) != true)) {
                    this.RightMetaField = value;
                    this.RaisePropertyChanged("RightMeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RightName {
            get {
                return this.RightNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RightNameField, value) != true)) {
                    this.RightNameField = value;
                    this.RaisePropertyChanged("RightName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RightType {
            get {
                return this.RightTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RightTypeField, value) != true)) {
                    this.RightTypeField = value;
                    this.RaisePropertyChanged("RightType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRightInfo", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.User")]
    [System.SerializableAttribute()]
    public partial class UserRightInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DisplayOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FatherRightIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HaveRightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RightIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RightNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisplayOrder {
            get {
                return this.DisplayOrderField;
            }
            set {
                if ((this.DisplayOrderField.Equals(value) != true)) {
                    this.DisplayOrderField = value;
                    this.RaisePropertyChanged("DisplayOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FatherRightID {
            get {
                return this.FatherRightIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FatherRightIDField, value) != true)) {
                    this.FatherRightIDField = value;
                    this.RaisePropertyChanged("FatherRightID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HaveRight {
            get {
                return this.HaveRightField;
            }
            set {
                if ((this.HaveRightField.Equals(value) != true)) {
                    this.HaveRightField = value;
                    this.RaisePropertyChanged("HaveRight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RightID {
            get {
                return this.RightIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RightIDField, value) != true)) {
                    this.RightIDField = value;
                    this.RaisePropertyChanged("RightID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RightName {
            get {
                return this.RightNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RightNameField, value) != true)) {
                    this.RightNameField = value;
                    this.RaisePropertyChanged("RightName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserQueryModelInfo", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.User")]
    [System.SerializableAttribute()]
    public partial class UserQueryModelInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HaveRightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryModelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryModelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryModelNamespaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryModelTitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HaveRight {
            get {
                return this.HaveRightField;
            }
            set {
                if ((this.HaveRightField.Equals(value) != true)) {
                    this.HaveRightField = value;
                    this.RaisePropertyChanged("HaveRight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueryModelID {
            get {
                return this.QueryModelIDField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryModelIDField, value) != true)) {
                    this.QueryModelIDField = value;
                    this.RaisePropertyChanged("QueryModelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueryModelName {
            get {
                return this.QueryModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryModelNameField, value) != true)) {
                    this.QueryModelNameField = value;
                    this.RaisePropertyChanged("QueryModelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueryModelNamespace {
            get {
                return this.QueryModelNamespaceField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryModelNamespaceField, value) != true)) {
                    this.QueryModelNamespaceField = value;
                    this.RaisePropertyChanged("QueryModelNamespace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueryModelTitle {
            get {
                return this.QueryModelTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryModelTitleField, value) != true)) {
                    this.QueryModelTitleField = value;
                    this.RaisePropertyChanged("QueryModelTitle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserPostInfo", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.User", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class UserPostInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoPost UserPostField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoPost UserPost {
            get {
                return this.UserPostField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPostField, value) != true)) {
                    this.UserPostField = value;
                    this.RaisePropertyChanged("UserPost");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SinoOrganize", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.Authorize")]
    [System.SerializableAttribute()]
    public partial class SinoOrganize : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanSelecetedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DWDMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DisplayOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FatherCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunctionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanSeleceted {
            get {
                return this.CanSelecetedField;
            }
            set {
                if ((this.CanSelecetedField.Equals(value) != true)) {
                    this.CanSelecetedField = value;
                    this.RaisePropertyChanged("CanSeleceted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DWDM {
            get {
                return this.DWDMField;
            }
            set {
                if ((object.ReferenceEquals(this.DWDMField, value) != true)) {
                    this.DWDMField = value;
                    this.RaisePropertyChanged("DWDM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisplayOrder {
            get {
                return this.DisplayOrderField;
            }
            set {
                if ((this.DisplayOrderField.Equals(value) != true)) {
                    this.DisplayOrderField = value;
                    this.RaisePropertyChanged("DisplayOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FatherCode {
            get {
                return this.FatherCodeField;
            }
            set {
                if ((this.FatherCodeField.Equals(value) != true)) {
                    this.FatherCodeField = value;
                    this.RaisePropertyChanged("FatherCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Function {
            get {
                return this.FunctionField;
            }
            set {
                if ((object.ReferenceEquals(this.FunctionField, value) != true)) {
                    this.FunctionField = value;
                    this.RaisePropertyChanged("Function");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SinoPost", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.Authorize")]
    [System.SerializableAttribute()]
    public partial class SinoPost : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DisplayOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDefaultPostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostDWDMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostDWGUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostDWMCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostDescriptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostDwIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, SinoSysWatchService.Application.SinoSZJSUserManagerService.UserRightItem> RightsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoRole[] RolesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecretLevelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisplayOrder {
            get {
                return this.DisplayOrderField;
            }
            set {
                if ((this.DisplayOrderField.Equals(value) != true)) {
                    this.DisplayOrderField = value;
                    this.RaisePropertyChanged("DisplayOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDefaultPost {
            get {
                return this.IsDefaultPostField;
            }
            set {
                if ((this.IsDefaultPostField.Equals(value) != true)) {
                    this.IsDefaultPostField = value;
                    this.RaisePropertyChanged("IsDefaultPost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostDWDM {
            get {
                return this.PostDWDMField;
            }
            set {
                if ((object.ReferenceEquals(this.PostDWDMField, value) != true)) {
                    this.PostDWDMField = value;
                    this.RaisePropertyChanged("PostDWDM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostDWGUID {
            get {
                return this.PostDWGUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PostDWGUIDField, value) != true)) {
                    this.PostDWGUIDField = value;
                    this.RaisePropertyChanged("PostDWGUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostDWMC {
            get {
                return this.PostDWMCField;
            }
            set {
                if ((object.ReferenceEquals(this.PostDWMCField, value) != true)) {
                    this.PostDWMCField = value;
                    this.RaisePropertyChanged("PostDWMC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostDescript {
            get {
                return this.PostDescriptField;
            }
            set {
                if ((object.ReferenceEquals(this.PostDescriptField, value) != true)) {
                    this.PostDescriptField = value;
                    this.RaisePropertyChanged("PostDescript");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostDwID {
            get {
                return this.PostDwIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PostDwIDField, value) != true)) {
                    this.PostDwIDField = value;
                    this.RaisePropertyChanged("PostDwID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostID {
            get {
                return this.PostIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PostIDField, value) != true)) {
                    this.PostIDField = value;
                    this.RaisePropertyChanged("PostID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostName {
            get {
                return this.PostNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PostNameField, value) != true)) {
                    this.PostNameField = value;
                    this.RaisePropertyChanged("PostName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, SinoSysWatchService.Application.SinoSZJSUserManagerService.UserRightItem> Rights {
            get {
                return this.RightsField;
            }
            set {
                if ((object.ReferenceEquals(this.RightsField, value) != true)) {
                    this.RightsField = value;
                    this.RaisePropertyChanged("Rights");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoRole[] Roles {
            get {
                return this.RolesField;
            }
            set {
                if ((object.ReferenceEquals(this.RolesField, value) != true)) {
                    this.RolesField = value;
                    this.RaisePropertyChanged("Roles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecretLevel {
            get {
                return this.SecretLevelField;
            }
            set {
                if ((this.SecretLevelField.Equals(value) != true)) {
                    this.SecretLevelField = value;
                    this.RaisePropertyChanged("SecretLevel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRightItem", Namespace="http://schemas.datacontract.org/2004/07/SinoSZJS.Base.Authorize", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class UserRightItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoRightItem RightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Level {
            get {
                return this.LevelField;
            }
            set {
                if ((this.LevelField.Equals(value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoRightItem Right {
            get {
                return this.RightField;
            }
            set {
                if ((object.ReferenceEquals(this.RightField, value) != true)) {
                    this.RightField = value;
                    this.RaisePropertyChanged("Right");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SinoSZJSUserManagerService.IUserManagerService")]
    public interface IUserManagerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/HeartBeat", ReplyAction="http://tempuri.org/IUserManagerService/HeartBeatResponse")]
        bool HeartBeat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/SaveUserMapping", ReplyAction="http://tempuri.org/IUserManagerService/SaveUserMappingResponse")]
        bool SaveUserMapping(string TRD_YHID, string JSYW_YHID, string TRD_YHM, string TRD_XM, string JSYW_XM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/GetTRDUserInfo", ReplyAction="http://tempuri.org/IUserManagerService/GetTRDUserInfoResponse")]
        string GetTRDUserInfo(string _logonName, string dwid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/GetUserListMapping", ReplyAction="http://tempuri.org/IUserManagerService/GetUserListMappingResponse")]
        SinoSysWatchService.Application.SinoSZJSUserManagerService.UserMappingInfo[] GetUserListMapping(decimal _orgid, decimal _levelNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/GetUserListInOrg", ReplyAction="http://tempuri.org/IUserManagerService/GetUserListInOrgResponse")]
        SinoSysWatchService.Application.SinoSZJSUserManagerService.UserBaseInfo[] GetUserListInOrg(decimal _orgid, decimal _levelNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/GetUserMobileList", ReplyAction="http://tempuri.org/IUserManagerService/GetUserMobileListResponse")]
        SinoSysWatchService.Application.SinoSZJSUserManagerService.UserExtInfo[] GetUserMobileList(decimal _orgid, decimal _LevelNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/GetPersionListInOrg", ReplyAction="http://tempuri.org/IUserManagerService/GetPersionListInOrgResponse")]
        SinoSysWatchService.Application.SinoSZJSUserManagerService.PersonBaseInfo[] GetPersionListInOrg(decimal _orgid, decimal _levelNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/RegisterUser", ReplyAction="http://tempuri.org/IUserManagerService/RegisterUserResponse")]
        bool RegisterUser(SinoSysWatchService.Application.SinoSZJSUserManagerService.PersonBaseInfo _personBaseInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/GetRoleList", ReplyAction="http://tempuri.org/IUserManagerService/GetRoleListResponse")]
        SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoRole[] GetRoleList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/AddNewRole", ReplyAction="http://tempuri.org/IUserManagerService/AddNewRoleResponse")]
        bool AddNewRole(SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoRole _newRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/GetRightListByRoleID", ReplyAction="http://tempuri.org/IUserManagerService/GetRightListByRoleIDResponse")]
        SinoSysWatchService.Application.SinoSZJSUserManagerService.UserRightInfo[] GetRightListByRoleID(string _roleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/GetModelRightListByRoleID", ReplyAction="http://tempuri.org/IUserManagerService/GetModelRightListByRoleIDResponse")]
        SinoSysWatchService.Application.SinoSZJSUserManagerService.UserQueryModelInfo[] GetModelRightListByRoleID(string _roleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/SaveRightsOfRole", ReplyAction="http://tempuri.org/IUserManagerService/SaveRightsOfRoleResponse")]
        bool SaveRightsOfRole(SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoRole _role, SinoSysWatchService.Application.SinoSZJSUserManagerService.UserRightInfo[] _functionRights, SinoSysWatchService.Application.SinoSZJSUserManagerService.UserQueryModelInfo[] _modelRights);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/DeleteRole", ReplyAction="http://tempuri.org/IUserManagerService/DeleteRoleResponse")]
        bool DeleteRole(SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoRole _role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/GetPostListInOrg", ReplyAction="http://tempuri.org/IUserManagerService/GetPostListInOrgResponse")]
        SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoPost[] GetPostListInOrg(SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoOrganize CurrentOrg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/AddPostOfOrg", ReplyAction="http://tempuri.org/IUserManagerService/AddPostOfOrgResponse")]
        bool AddPostOfOrg(string _postName, string _postDescript, int _PostLevel, decimal _orgID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/DelPostOfOrg", ReplyAction="http://tempuri.org/IUserManagerService/DelPostOfOrgResponse")]
        bool DelPostOfOrg(string _postID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/ModifyPostOfOrg", ReplyAction="http://tempuri.org/IUserManagerService/ModifyPostOfOrgResponse")]
        bool ModifyPostOfOrg(string _postName, string _postDescript, int _PostLevel, string _postID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/GetRoleOfPost", ReplyAction="http://tempuri.org/IUserManagerService/GetRoleOfPostResponse")]
        SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoRole[] GetRoleOfPost(string _postID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/SaveRolesOfPost", ReplyAction="http://tempuri.org/IUserManagerService/SaveRolesOfPostResponse")]
        bool SaveRolesOfPost(SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoRole[] _roleList, string _postID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/PastePostToOrg", ReplyAction="http://tempuri.org/IUserManagerService/PastePostToOrgResponse")]
        bool PastePostToOrg(SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoPost[] _clipPad, SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoOrganize _org);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/GetRightListByPostID", ReplyAction="http://tempuri.org/IUserManagerService/GetRightListByPostIDResponse")]
        SinoSysWatchService.Application.SinoSZJSUserManagerService.UserRightInfo[] GetRightListByPostID(string _postID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/GetModelRightListByPostID", ReplyAction="http://tempuri.org/IUserManagerService/GetModelRightListByPostIDResponse")]
        SinoSysWatchService.Application.SinoSZJSUserManagerService.UserQueryModelInfo[] GetModelRightListByPostID(string _postID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/GetPostListByUserID", ReplyAction="http://tempuri.org/IUserManagerService/GetPostListByUserIDResponse")]
        SinoSysWatchService.Application.SinoSZJSUserManagerService.UserPostInfo[] GetPostListByUserID(string _userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/IsExistUserPost", ReplyAction="http://tempuri.org/IUserManagerService/IsExistUserPostResponse")]
        bool IsExistUserPost(string _userID, string _postID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/AddUserPost", ReplyAction="http://tempuri.org/IUserManagerService/AddUserPostResponse")]
        bool AddUserPost(string _userID, string _postID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/UnRegisterUser", ReplyAction="http://tempuri.org/IUserManagerService/UnRegisterUserResponse")]
        bool UnRegisterUser(string _userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/DeleteUserPost", ReplyAction="http://tempuri.org/IUserManagerService/DeleteUserPostResponse")]
        bool DeleteUserPost(string _userID, string _postID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/SetDefaultUserPost", ReplyAction="http://tempuri.org/IUserManagerService/SetDefaultUserPostResponse")]
        bool SetDefaultUserPost(string _userID, string _postID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/GetUsersOfPost", ReplyAction="http://tempuri.org/IUserManagerService/GetUsersOfPostResponse")]
        SinoSysWatchService.Application.SinoSZJSUserManagerService.UserBaseInfo[] GetUsersOfPost(string _postID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/DeleteUserOfPost", ReplyAction="http://tempuri.org/IUserManagerService/DeleteUserOfPostResponse")]
        bool DeleteUserOfPost(string _postID, string _userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/IsExistYHM", ReplyAction="http://tempuri.org/IUserManagerService/IsExistYHMResponse")]
        bool IsExistYHM(string _yhm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/AddUserInfo", ReplyAction="http://tempuri.org/IUserManagerService/AddUserInfoResponse")]
        bool AddUserInfo(string YHM, string XM, string XB, string SFZH, decimal SSDW, string DWGUID, string HGGH, string JH, string ZWMC, string ZWJB, string EMAIL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/GetDWGUID", ReplyAction="http://tempuri.org/IUserManagerService/GetDWGUIDResponse")]
        string GetDWGUID(decimal DWID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/AddNewOrg", ReplyAction="http://tempuri.org/IUserManagerService/AddNewOrgResponse")]
        bool AddNewOrg(string ShotName, string FullName, SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoOrganize FatherOrg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/DelOrg", ReplyAction="http://tempuri.org/IUserManagerService/DelOrgResponse")]
        bool DelOrg(SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoOrganize sinoOrganize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/IsExistChildOrg", ReplyAction="http://tempuri.org/IUserManagerService/IsExistChildOrgResponse")]
        bool IsExistChildOrg(decimal DWID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagerService/SaveUserExtInfo", ReplyAction="http://tempuri.org/IUserManagerService/SaveUserExtInfoResponse")]
        bool SaveUserExtInfo(string LogonName, string Mobile, string Email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserManagerServiceChannel : SinoSysWatchService.Application.SinoSZJSUserManagerService.IUserManagerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserManagerServiceClient : System.ServiceModel.ClientBase<SinoSysWatchService.Application.SinoSZJSUserManagerService.IUserManagerService>, SinoSysWatchService.Application.SinoSZJSUserManagerService.IUserManagerService {
        
        public UserManagerServiceClient() {
        }
        
        public UserManagerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserManagerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool HeartBeat() {
            return base.Channel.HeartBeat();
        }
        
        public bool SaveUserMapping(string TRD_YHID, string JSYW_YHID, string TRD_YHM, string TRD_XM, string JSYW_XM) {
            return base.Channel.SaveUserMapping(TRD_YHID, JSYW_YHID, TRD_YHM, TRD_XM, JSYW_XM);
        }
        
        public string GetTRDUserInfo(string _logonName, string dwid) {
            return base.Channel.GetTRDUserInfo(_logonName, dwid);
        }
        
        public SinoSysWatchService.Application.SinoSZJSUserManagerService.UserMappingInfo[] GetUserListMapping(decimal _orgid, decimal _levelNum) {
            return base.Channel.GetUserListMapping(_orgid, _levelNum);
        }
        
        public SinoSysWatchService.Application.SinoSZJSUserManagerService.UserBaseInfo[] GetUserListInOrg(decimal _orgid, decimal _levelNum) {
            return base.Channel.GetUserListInOrg(_orgid, _levelNum);
        }
        
        public SinoSysWatchService.Application.SinoSZJSUserManagerService.UserExtInfo[] GetUserMobileList(decimal _orgid, decimal _LevelNum) {
            return base.Channel.GetUserMobileList(_orgid, _LevelNum);
        }
        
        public SinoSysWatchService.Application.SinoSZJSUserManagerService.PersonBaseInfo[] GetPersionListInOrg(decimal _orgid, decimal _levelNum) {
            return base.Channel.GetPersionListInOrg(_orgid, _levelNum);
        }
        
        public bool RegisterUser(SinoSysWatchService.Application.SinoSZJSUserManagerService.PersonBaseInfo _personBaseInfo) {
            return base.Channel.RegisterUser(_personBaseInfo);
        }
        
        public SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoRole[] GetRoleList() {
            return base.Channel.GetRoleList();
        }
        
        public bool AddNewRole(SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoRole _newRole) {
            return base.Channel.AddNewRole(_newRole);
        }
        
        public SinoSysWatchService.Application.SinoSZJSUserManagerService.UserRightInfo[] GetRightListByRoleID(string _roleID) {
            return base.Channel.GetRightListByRoleID(_roleID);
        }
        
        public SinoSysWatchService.Application.SinoSZJSUserManagerService.UserQueryModelInfo[] GetModelRightListByRoleID(string _roleID) {
            return base.Channel.GetModelRightListByRoleID(_roleID);
        }
        
        public bool SaveRightsOfRole(SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoRole _role, SinoSysWatchService.Application.SinoSZJSUserManagerService.UserRightInfo[] _functionRights, SinoSysWatchService.Application.SinoSZJSUserManagerService.UserQueryModelInfo[] _modelRights) {
            return base.Channel.SaveRightsOfRole(_role, _functionRights, _modelRights);
        }
        
        public bool DeleteRole(SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoRole _role) {
            return base.Channel.DeleteRole(_role);
        }
        
        public SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoPost[] GetPostListInOrg(SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoOrganize CurrentOrg) {
            return base.Channel.GetPostListInOrg(CurrentOrg);
        }
        
        public bool AddPostOfOrg(string _postName, string _postDescript, int _PostLevel, decimal _orgID) {
            return base.Channel.AddPostOfOrg(_postName, _postDescript, _PostLevel, _orgID);
        }
        
        public bool DelPostOfOrg(string _postID) {
            return base.Channel.DelPostOfOrg(_postID);
        }
        
        public bool ModifyPostOfOrg(string _postName, string _postDescript, int _PostLevel, string _postID) {
            return base.Channel.ModifyPostOfOrg(_postName, _postDescript, _PostLevel, _postID);
        }
        
        public SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoRole[] GetRoleOfPost(string _postID) {
            return base.Channel.GetRoleOfPost(_postID);
        }
        
        public bool SaveRolesOfPost(SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoRole[] _roleList, string _postID) {
            return base.Channel.SaveRolesOfPost(_roleList, _postID);
        }
        
        public bool PastePostToOrg(SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoPost[] _clipPad, SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoOrganize _org) {
            return base.Channel.PastePostToOrg(_clipPad, _org);
        }
        
        public SinoSysWatchService.Application.SinoSZJSUserManagerService.UserRightInfo[] GetRightListByPostID(string _postID) {
            return base.Channel.GetRightListByPostID(_postID);
        }
        
        public SinoSysWatchService.Application.SinoSZJSUserManagerService.UserQueryModelInfo[] GetModelRightListByPostID(string _postID) {
            return base.Channel.GetModelRightListByPostID(_postID);
        }
        
        public SinoSysWatchService.Application.SinoSZJSUserManagerService.UserPostInfo[] GetPostListByUserID(string _userID) {
            return base.Channel.GetPostListByUserID(_userID);
        }
        
        public bool IsExistUserPost(string _userID, string _postID) {
            return base.Channel.IsExistUserPost(_userID, _postID);
        }
        
        public bool AddUserPost(string _userID, string _postID) {
            return base.Channel.AddUserPost(_userID, _postID);
        }
        
        public bool UnRegisterUser(string _userID) {
            return base.Channel.UnRegisterUser(_userID);
        }
        
        public bool DeleteUserPost(string _userID, string _postID) {
            return base.Channel.DeleteUserPost(_userID, _postID);
        }
        
        public bool SetDefaultUserPost(string _userID, string _postID) {
            return base.Channel.SetDefaultUserPost(_userID, _postID);
        }
        
        public SinoSysWatchService.Application.SinoSZJSUserManagerService.UserBaseInfo[] GetUsersOfPost(string _postID) {
            return base.Channel.GetUsersOfPost(_postID);
        }
        
        public bool DeleteUserOfPost(string _postID, string _userID) {
            return base.Channel.DeleteUserOfPost(_postID, _userID);
        }
        
        public bool IsExistYHM(string _yhm) {
            return base.Channel.IsExistYHM(_yhm);
        }
        
        public bool AddUserInfo(string YHM, string XM, string XB, string SFZH, decimal SSDW, string DWGUID, string HGGH, string JH, string ZWMC, string ZWJB, string EMAIL) {
            return base.Channel.AddUserInfo(YHM, XM, XB, SFZH, SSDW, DWGUID, HGGH, JH, ZWMC, ZWJB, EMAIL);
        }
        
        public string GetDWGUID(decimal DWID) {
            return base.Channel.GetDWGUID(DWID);
        }
        
        public bool AddNewOrg(string ShotName, string FullName, SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoOrganize FatherOrg) {
            return base.Channel.AddNewOrg(ShotName, FullName, FatherOrg);
        }
        
        public bool DelOrg(SinoSysWatchService.Application.SinoSZJSUserManagerService.SinoOrganize sinoOrganize) {
            return base.Channel.DelOrg(sinoOrganize);
        }
        
        public bool IsExistChildOrg(decimal DWID) {
            return base.Channel.IsExistChildOrg(DWID);
        }
        
        public bool SaveUserExtInfo(string LogonName, string Mobile, string Email) {
            return base.Channel.SaveUserExtInfo(LogonName, Mobile, Email);
        }
    }
}
