//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinoSZClientBase.MetaDataQueryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MetaDataQueryService.IMetaDataQueryService")]
    public interface IMetaDataQueryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/ChangeDataCheckRule", ReplyAction="http://tempuri.org/IMetaDataQueryService/ChangeDataCheckRuleResponse")]
        bool ChangeDataCheckRule(string _ruleID, string _gzsf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetInputModelBlankData", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetInputModelBlankDataResponse")]
        System.Data.DataTable GetInputModelBlankData(string _initGuideLineID, string _getBlankGuideLineID, SinoSZJS.Base.MetaData.QueryModel.MDQuery_GuideLineParameter[] _params);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/SaveDataByInputModel", ReplyAction="http://tempuri.org/IMetaDataQueryService/SaveDataByInputModelResponse")]
        bool SaveDataByInputModel(string _inputModelName, System.Data.DataTable _changedData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/TestComputeExpress", ReplyAction="http://tempuri.org/IMetaDataQueryService/TestComputeExpressResponse")]
        void TestComputeExpress(string ExpressionString, SinoSZJS.Base.MetaData.QueryModel.MDModel_Table TableDefine, ref string QueryString, ref string resultDataType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/SaveComputeFieldDefine", ReplyAction="http://tempuri.org/IMetaDataQueryService/SaveComputeFieldDefineResponse")]
        void SaveComputeFieldDefine(string DisplayName, string Description, string Expression, string QueryString, string ResultDataType, string TableName, string ModelName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetPersonSavedComputField", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetPersonSavedComputFieldResponse")]
        SinoSZJS.Base.MetaData.QueryModel.MDQuery_ComputeColumnDefine[] GetPersonSavedComputField(string ModelName, string TableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetFunctionList", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetFunctionListResponse")]
        SinoSZJS.Base.MetaData.Define.MD_FUNCTION[] GetFunctionList(int _type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/TestStatisticsExpress", ReplyAction="http://tempuri.org/IMetaDataQueryService/TestStatisticsExpressResponse")]
        void TestStatisticsExpress(string TableName, SinoSZJS.Base.MetaData.QueryModel.MDModel_Table_Column _column, SinoSZJS.Base.MetaData.Define.MD_FUNCTION FunctionDefine, ref string queryString, ref string resultDataType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetQueryModelDescription", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetQueryModelDescriptionResponse")]
        string GetQueryModelDescription(string _modelName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetRuleList", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetRuleListResponse")]
        System.Data.DataSet GetRuleList(string QueryModelName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/ImportRule", ReplyAction="http://tempuri.org/IMetaDataQueryService/ImportRuleResponse")]
        void ImportRule(string SrcRuleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/RecoverRuleDefine", ReplyAction="http://tempuri.org/IMetaDataQueryService/RecoverRuleDefineResponse")]
        void RecoverRuleDefine(string TargetRuleID, string SrcRuleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetSjshInfo_HGJS", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetSjshInfo_HGJSResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.DataCompare.MDCompare_Request))]
        string GetSjshInfo_HGJS(SinoSZJS.Base.MetaData.QueryModel.MDQuery_Request _queryRequest, string MainKeyID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetSjsh_HisData", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetSjsh_HisDataResponse")]
        SinoSZJS.Base.Report.DataCheck.ReportHisDataRow[] GetSjsh_HisData(string QueryModelName, string MainKeyID, string WHXH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetDataCheckBoardList", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetDataCheckBoardListResponse")]
        System.Data.DataSet GetDataCheckBoardList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/InsertNewDataCheckMsg", ReplyAction="http://tempuri.org/IMetaDataQueryService/InsertNewDataCheckMsgResponse")]
        bool InsertNewDataCheckMsg(string _shjlid, string _title, string _context, string _cddw, string _tel, string _email, decimal _sfkj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetSjshInfo_DWID", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetSjshInfo_DWIDResponse")]
        string GetSjshInfo_DWID(string _shjlid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetDataCheckMsg", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetDataCheckMsgResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MDQuery_GuideLineParameter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MDQuery_GuideLineParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MD_GuideLineParameter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MDModel_Table))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MDModel_Table_Column))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.QueryColumnType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MDModel_Table_Column[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MDQuery_ComputeColumnDefine[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MDQuery_ComputeColumnDefine))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MDQuery_Request))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MDQuery_ResultTable[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MDQuery_ResultTable))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MDQuery_TableColumn[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MDQuery_TableColumn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MDQuery_ColumnSource))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MDQuery_ConditionItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MDQuery_ConditionItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MD_GuideLine_ParamSetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MDQuery_ChildTableRowCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MDQuery_ChildTableRowCount))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MDSearch_Column[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MDSearch_Column))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MDSearch_ResultDataIndex[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MDSearch_ResultDataIndex))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MD_GuideLine[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MD_GuideLine))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MD_GuideLineDetailDefine[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MD_GuideLineDetailDefine))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MD_GuideLineGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MD_GuideLineParameter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MD_GuideLineFieldGroup[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MD_GuideLineFieldGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MD_GuideLineFieldName[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MD_GuideLineFieldName))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MDQuery_Task[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.QueryModel.MDQuery_Task))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, SinoSZJS.Base.MetaData.QueryModel.MDModel_Table_Column>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, SinoSZJS.Base.MetaData.DataCompare.MDCompare_ConditionItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_ViewTableColumn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_TableColumn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_RefTable))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_Namespace))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_Nodes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_Namespace[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_QueryModel[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_QueryModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_ViewTable[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_ViewTable))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_ViewTableColumn[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_Table))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_TableColumn[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_View2App[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_View2App))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_View_GuideLine[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_View_GuideLine))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_View2ViewGroup[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_View2ViewGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_View2View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_View2View))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_RefTable[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_Table[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_FUNCTION[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_FUNCTION))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_ConceptGroup[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_ConceptGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_ConceptItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.Define.MD_ConceptItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.EnumDefine.MDType_DisplayType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.EnumDefine.MDType_ViewTableRelation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.EnumDefine.MDType_ViewTable))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.EnumDefine.MDType_RefDownloadMode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.EnumDefine.MDType_RefParamMode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.Report.DataCheck.ReportHisDataRow[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.Report.DataCheck.ReportHisDataRow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.DataCheck.MD_CheckRule[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.DataCheck.MD_CheckRule))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.InputModel.MD_InputModel_ColumnGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.InputModel.MD_InputModel_Column[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.InputModel.MD_InputModel_Column))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.InputModel.MD_InputModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.InputModel.MD_InputModel_Child[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.InputModel.MD_InputModel_Child))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.InputModel.MD_InputModel_ChildParam[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.InputModel.MD_InputModel_ChildParam))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.InputModel.MD_InputModel_ColumnGroup[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.InputModel.MD_InputModel_SaveTable[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.InputModel.MD_InputModel_SaveTable))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.InputModel.MD_InputModel_SaveTableColumn[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.InputModel.MD_InputModel_SaveTableColumn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.DataCompare.MDCompare_Request))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.DataCompare.MDCompare_ConditionItem))]
        SinoSZJS.Base.MetaData.DataCheck.MD_DataCheckMsg GetDataCheckMsg(string _ggjlid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/SendDataCheckMsgFK", ReplyAction="http://tempuri.org/IMetaDataQueryService/SendDataCheckMsgFKResponse")]
        bool SendDataCheckMsgFK(string _ggjlid, string _fkjg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/UpdateDataCheckMsg", ReplyAction="http://tempuri.org/IMetaDataQueryService/UpdateDataCheckMsgResponse")]
        bool UpdateDataCheckMsg(string _ggjlid, string _title, string _context, string _cddw, string _tel, string _email, decimal _sfkj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/DeleteDataCheckMsg", ReplyAction="http://tempuri.org/IMetaDataQueryService/DeleteDataCheckMsgResponse")]
        bool DeleteDataCheckMsg(string _ggjlid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetGuideLineParamSetting", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetGuideLineParamSettingResponse")]
        SinoSZJS.Base.MetaData.QueryModel.MD_GuideLine_ParamSetting GetGuideLineParamSetting(string _guideLineID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/SaveGuideLineParamSetting", ReplyAction="http://tempuri.org/IMetaDataQueryService/SaveGuideLineParamSettingResponse")]
        bool SaveGuideLineParamSetting(SinoSZJS.Base.MetaData.QueryModel.MD_GuideLine_ParamSetting _paramSetting, SinoSZJS.Base.MetaData.QueryModel.MDQuery_GuideLineParameter[] _paramters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetInputGroupByID", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetInputGroupByIDResponse")]
        SinoSZJS.Base.InputModel.MD_InputModel_ColumnGroup GetInputGroupByID(string InputGroupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetInputModelByID", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetInputModelByIDResponse")]
        SinoSZJS.Base.InputModel.MD_InputModel GetInputModelByID(string InputModelID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/DelComputeFieldDefine", ReplyAction="http://tempuri.org/IMetaDataQueryService/DelComputeFieldDefineResponse")]
        bool DelComputeFieldDefine(string ColumnName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/CompareData", ReplyAction="http://tempuri.org/IMetaDataQueryService/CompareDataResponse")]
        System.Data.DataSet CompareData(SinoSZJS.Base.MetaData.DataCompare.MDCompare_Request compareRequest, System.Data.DataTable srcData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetAttachFileName", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetAttachFileNameResponse")]
        string GetAttachFileName(string IndexString, string FieldName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetAttachFileBytes", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetAttachFileBytesResponse")]
        byte[] GetAttachFileBytes(string IndexString, string FieldName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetFLWSFileName", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetFLWSFileNameResponse")]
        string GetFLWSFileName(string _indexString, string FieldName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetFLWSFileBytes", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetFLWSFileBytesResponse")]
        byte[] GetFLWSFileBytes(string _indexString, string FieldName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetTaskQueryLog", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetTaskQueryLogResponse")]
        System.Data.DataTable GetTaskQueryLog(string TaskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/ChangeQueryTaskRequestTime", ReplyAction="http://tempuri.org/IMetaDataQueryService/ChangeQueryTaskRequestTimeResponse")]
        bool ChangeQueryTaskRequestTime(string TaskID, System.DateTime RequestTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/RebuildGuideLineParamSetting", ReplyAction="http://tempuri.org/IMetaDataQueryService/RebuildGuideLineParamSettingResponse")]
        bool RebuildGuideLineParamSetting(string GuideLineID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetMDQueryModelDefine", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetMDQueryModelDefineResponse")]
        SinoSZJS.Base.MetaData.Define.MD_QueryModel GetMDQueryModelDefine(string _queryModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/QueryData", ReplyAction="http://tempuri.org/IMetaDataQueryService/QueryDataResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.DataCompare.MDCompare_Request))]
        System.Data.DataSet QueryData(SinoSZJS.Base.MetaData.QueryModel.MDQuery_Request mDQuery_Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetMainTableDataByKey", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetMainTableDataByKeyResponse")]
        System.Data.DataTable GetMainTableDataByKey(string _queryModelName, string _mainTableName, string _keyid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetChildTableDataByKey", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetChildTableDataByKeyResponse")]
        System.Data.DataTable GetChildTableDataByKey(string _queryModelName, string _childTableName, string _keyid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetChildTableCountByKey", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetChildTableCountByKeyResponse")]
        int GetChildTableCountByKey(string _queryModelName, string _childTableName, string _keyid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetChildRowCountList", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetChildRowCountListResponse")]
        SinoSZJS.Base.MetaData.QueryModel.MDQuery_ChildTableRowCount[] GetChildRowCountList(string _queryModelName, string _keyid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetConceptList", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetConceptListResponse")]
        SinoSZJS.Base.MetaData.Define.MD_ConceptGroup[] GetConceptList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetQueryModels", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetQueryModelsResponse")]
        SinoSZJS.Base.MetaData.Define.MD_QueryModel[] GetQueryModels(string _queryModelNames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetSearchResultColumn", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetSearchResultColumnResponse")]
        SinoSZJS.Base.MetaData.QueryModel.MDSearch_Column[] GetSearchResultColumn(string _searchText, int _searchType, string _searchConceptGroup, string _queryModelName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetSearchResult", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetSearchResultResponse")]
        SinoSZJS.Base.MetaData.QueryModel.MDSearch_ResultDataIndex[] GetSearchResult(string _searchText, int _searchType, SinoSZJS.Base.MetaData.QueryModel.MDSearch_Column _sc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetMainTableKeyByChildKey", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetMainTableKeyByChildKeyResponse")]
        string GetMainTableKeyByChildKey(SinoSZJS.Base.MetaData.QueryModel.MDSearch_Column _childColumn, string _childKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetMainTableKeyByColumnCondition", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetMainTableKeyByColumnConditionResponse" +
            "")]
        string GetMainTableKeyByColumnCondition(string _modelName, string _columnName, string _data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetRootGuideLineList", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetRootGuideLineListResponse")]
        SinoSZJS.Base.MetaData.QueryModel.MD_GuideLine[] GetRootGuideLineList(string rootGuideLines);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetGuideLineListByFatherID", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetGuideLineListByFatherIDResponse")]
        SinoSZJS.Base.MetaData.QueryModel.MD_GuideLine[] GetGuideLineListByFatherID(string _fatherID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/QueryGuideLine", ReplyAction="http://tempuri.org/IMetaDataQueryService/QueryGuideLineResponse")]
        System.Data.DataTable QueryGuideLine(string _guideLineID, SinoSZJS.Base.MetaData.QueryModel.MDQuery_GuideLineParameter[] _param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/QueryGuideLineByDefault", ReplyAction="http://tempuri.org/IMetaDataQueryService/QueryGuideLineByDefaultResponse")]
        System.Data.DataTable QueryGuideLineByDefault(string _guideLineID, SinoSZJS.Base.MetaData.QueryModel.MDQuery_GuideLineParameter[] _param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/QueryGuideLineResultCount", ReplyAction="http://tempuri.org/IMetaDataQueryService/QueryGuideLineResultCountResponse")]
        int QueryGuideLineResultCount(string _guideLineID, SinoSZJS.Base.MetaData.QueryModel.MDQuery_GuideLineParameter[] _params);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetGuideLineByID", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetGuideLineByIDResponse")]
        SinoSZJS.Base.MetaData.QueryModel.MD_GuideLine GetGuideLineByID(string _guideLineID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/AddNewQueryTask", ReplyAction="http://tempuri.org/IMetaDataQueryService/AddNewQueryTaskResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.DataCompare.MDCompare_Request))]
        string AddNewQueryTask(string _taskName, SinoSZJS.Base.MetaData.QueryModel.MDQuery_Request _queryRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetQueryTaskRequestContext", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetQueryTaskRequestContextResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.DataCompare.MDCompare_Request))]
        SinoSZJS.Base.MetaData.QueryModel.MDQuery_Request GetQueryTaskRequestContext(string _taskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetQueryTaskList", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetQueryTaskListResponse")]
        SinoSZJS.Base.MetaData.QueryModel.MDQuery_Task[] GetQueryTaskList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetQueryTaskStateByID", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetQueryTaskStateByIDResponse")]
        SinoSZJS.Base.MetaData.QueryModel.MDQuery_Task GetQueryTaskStateByID(string _taskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/ClearQueryTask", ReplyAction="http://tempuri.org/IMetaDataQueryService/ClearQueryTaskResponse")]
        bool ClearQueryTask(string _taskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/LockQueryTaskResult", ReplyAction="http://tempuri.org/IMetaDataQueryService/LockQueryTaskResultResponse")]
        bool LockQueryTaskResult(string _taskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/CancleQueryTask", ReplyAction="http://tempuri.org/IMetaDataQueryService/CancleQueryTaskResponse")]
        bool CancleQueryTask(string _taskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetTaskQueryResult_DataSet", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetTaskQueryResult_DataSetResponse")]
        System.Data.DataSet GetTaskQueryResult_DataSet(string _taskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetTaskQueryResult_ORA", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetTaskQueryResult_ORAResponse")]
        System.Data.DataSet GetTaskQueryResult_ORA(string _taskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetDataCheckRuleDefine", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetDataCheckRuleDefineResponse")]
        SinoSZJS.Base.MetaData.DataCheck.MD_CheckRule[] GetDataCheckRuleDefine(string QueryModelName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/SaveQuery", ReplyAction="http://tempuri.org/IMetaDataQueryService/SaveQueryResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.DataCompare.MDCompare_Request))]
        void SaveQuery(string SaveName, bool IsPublic, SinoSZJS.Base.MetaData.QueryModel.MDQuery_Request QueryRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetSaveQueryList", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetSaveQueryListResponse")]
        System.Data.DataTable GetSaveQueryList(string QueryModelName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/LoadQuery", ReplyAction="http://tempuri.org/IMetaDataQueryService/LoadQueryResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.DataCompare.MDCompare_Request))]
        SinoSZJS.Base.MetaData.QueryModel.MDQuery_Request LoadQuery(string SaveQueryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/QueryDataWithWHXH", ReplyAction="http://tempuri.org/IMetaDataQueryService/QueryDataWithWHXHResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinoSZJS.Base.MetaData.DataCompare.MDCompare_Request))]
        System.Data.DataTable QueryDataWithWHXH(SinoSZJS.Base.MetaData.QueryModel.MDQuery_Request _queryRequest, string _dwdm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetInputModelByName", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetInputModelByNameResponse")]
        SinoSZJS.Base.InputModel.MD_InputModel GetInputModelByName(string _modelName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/DelSavedQuery", ReplyAction="http://tempuri.org/IMetaDataQueryService/DelSavedQueryResponse")]
        bool DelSavedQuery(string _savedID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetUserLevel", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetUserLevelResponse")]
        string GetUserLevel();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetDataCheckInfo", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetDataCheckInfoResponse")]
        System.Data.DataTable GetDataCheckInfo(string _modelName, string _mainKey, ref string SHID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetDataCheckInfoJLID", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetDataCheckInfoJLIDResponse")]
        string GetDataCheckInfoJLID(string QueryModelName, string _mainkeyId, string _level, ref string SHID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/SaveDataCheckResult", ReplyAction="http://tempuri.org/IMetaDataQueryService/SaveDataCheckResultResponse")]
        string SaveDataCheckResult(string CurrentJLID, string CurrentLevel, string CurrentID, string _shjg, string _shr, string _xgyj, string WHXH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/GetDataCheckWHXH", ReplyAction="http://tempuri.org/IMetaDataQueryService/GetDataCheckWHXHResponse")]
        string GetDataCheckWHXH(string _tableName, string _mainColumn, string _mainKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/SaveNewDataCheckRule", ReplyAction="http://tempuri.org/IMetaDataQueryService/SaveNewDataCheckRuleResponse")]
        bool SaveNewDataCheckRule(string _ruleName, string _queryModelName, string _gzsf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetaDataQueryService/DelDataCheckRule", ReplyAction="http://tempuri.org/IMetaDataQueryService/DelDataCheckRuleResponse")]
        bool DelDataCheckRule(string _ruleID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMetaDataQueryServiceChannel : SinoSZClientBase.MetaDataQueryService.IMetaDataQueryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MetaDataQueryServiceClient : System.ServiceModel.ClientBase<SinoSZClientBase.MetaDataQueryService.IMetaDataQueryService>, SinoSZClientBase.MetaDataQueryService.IMetaDataQueryService {
        
        public MetaDataQueryServiceClient() {
        }
        
        public MetaDataQueryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MetaDataQueryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetaDataQueryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetaDataQueryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ChangeDataCheckRule(string _ruleID, string _gzsf) {
            return base.Channel.ChangeDataCheckRule(_ruleID, _gzsf);
        }
        
        public System.Data.DataTable GetInputModelBlankData(string _initGuideLineID, string _getBlankGuideLineID, SinoSZJS.Base.MetaData.QueryModel.MDQuery_GuideLineParameter[] _params) {
            return base.Channel.GetInputModelBlankData(_initGuideLineID, _getBlankGuideLineID, _params);
        }
        
        public bool SaveDataByInputModel(string _inputModelName, System.Data.DataTable _changedData) {
            return base.Channel.SaveDataByInputModel(_inputModelName, _changedData);
        }
        
        public void TestComputeExpress(string ExpressionString, SinoSZJS.Base.MetaData.QueryModel.MDModel_Table TableDefine, ref string QueryString, ref string resultDataType) {
            base.Channel.TestComputeExpress(ExpressionString, TableDefine, ref QueryString, ref resultDataType);
        }
        
        public void SaveComputeFieldDefine(string DisplayName, string Description, string Expression, string QueryString, string ResultDataType, string TableName, string ModelName) {
            base.Channel.SaveComputeFieldDefine(DisplayName, Description, Expression, QueryString, ResultDataType, TableName, ModelName);
        }
        
        public SinoSZJS.Base.MetaData.QueryModel.MDQuery_ComputeColumnDefine[] GetPersonSavedComputField(string ModelName, string TableName) {
            return base.Channel.GetPersonSavedComputField(ModelName, TableName);
        }
        
        public SinoSZJS.Base.MetaData.Define.MD_FUNCTION[] GetFunctionList(int _type) {
            return base.Channel.GetFunctionList(_type);
        }
        
        public void TestStatisticsExpress(string TableName, SinoSZJS.Base.MetaData.QueryModel.MDModel_Table_Column _column, SinoSZJS.Base.MetaData.Define.MD_FUNCTION FunctionDefine, ref string queryString, ref string resultDataType) {
            base.Channel.TestStatisticsExpress(TableName, _column, FunctionDefine, ref queryString, ref resultDataType);
        }
        
        public string GetQueryModelDescription(string _modelName) {
            return base.Channel.GetQueryModelDescription(_modelName);
        }
        
        public System.Data.DataSet GetRuleList(string QueryModelName) {
            return base.Channel.GetRuleList(QueryModelName);
        }
        
        public void ImportRule(string SrcRuleID) {
            base.Channel.ImportRule(SrcRuleID);
        }
        
        public void RecoverRuleDefine(string TargetRuleID, string SrcRuleID) {
            base.Channel.RecoverRuleDefine(TargetRuleID, SrcRuleID);
        }
        
        public string GetSjshInfo_HGJS(SinoSZJS.Base.MetaData.QueryModel.MDQuery_Request _queryRequest, string MainKeyID) {
            return base.Channel.GetSjshInfo_HGJS(_queryRequest, MainKeyID);
        }
        
        public SinoSZJS.Base.Report.DataCheck.ReportHisDataRow[] GetSjsh_HisData(string QueryModelName, string MainKeyID, string WHXH) {
            return base.Channel.GetSjsh_HisData(QueryModelName, MainKeyID, WHXH);
        }
        
        public System.Data.DataSet GetDataCheckBoardList() {
            return base.Channel.GetDataCheckBoardList();
        }
        
        public bool InsertNewDataCheckMsg(string _shjlid, string _title, string _context, string _cddw, string _tel, string _email, decimal _sfkj) {
            return base.Channel.InsertNewDataCheckMsg(_shjlid, _title, _context, _cddw, _tel, _email, _sfkj);
        }
        
        public string GetSjshInfo_DWID(string _shjlid) {
            return base.Channel.GetSjshInfo_DWID(_shjlid);
        }
        
        public SinoSZJS.Base.MetaData.DataCheck.MD_DataCheckMsg GetDataCheckMsg(string _ggjlid) {
            return base.Channel.GetDataCheckMsg(_ggjlid);
        }
        
        public bool SendDataCheckMsgFK(string _ggjlid, string _fkjg) {
            return base.Channel.SendDataCheckMsgFK(_ggjlid, _fkjg);
        }
        
        public bool UpdateDataCheckMsg(string _ggjlid, string _title, string _context, string _cddw, string _tel, string _email, decimal _sfkj) {
            return base.Channel.UpdateDataCheckMsg(_ggjlid, _title, _context, _cddw, _tel, _email, _sfkj);
        }
        
        public bool DeleteDataCheckMsg(string _ggjlid) {
            return base.Channel.DeleteDataCheckMsg(_ggjlid);
        }
        
        public SinoSZJS.Base.MetaData.QueryModel.MD_GuideLine_ParamSetting GetGuideLineParamSetting(string _guideLineID) {
            return base.Channel.GetGuideLineParamSetting(_guideLineID);
        }
        
        public bool SaveGuideLineParamSetting(SinoSZJS.Base.MetaData.QueryModel.MD_GuideLine_ParamSetting _paramSetting, SinoSZJS.Base.MetaData.QueryModel.MDQuery_GuideLineParameter[] _paramters) {
            return base.Channel.SaveGuideLineParamSetting(_paramSetting, _paramters);
        }
        
        public SinoSZJS.Base.InputModel.MD_InputModel_ColumnGroup GetInputGroupByID(string InputGroupID) {
            return base.Channel.GetInputGroupByID(InputGroupID);
        }
        
        public SinoSZJS.Base.InputModel.MD_InputModel GetInputModelByID(string InputModelID) {
            return base.Channel.GetInputModelByID(InputModelID);
        }
        
        public bool DelComputeFieldDefine(string ColumnName) {
            return base.Channel.DelComputeFieldDefine(ColumnName);
        }
        
        public System.Data.DataSet CompareData(SinoSZJS.Base.MetaData.DataCompare.MDCompare_Request compareRequest, System.Data.DataTable srcData) {
            return base.Channel.CompareData(compareRequest, srcData);
        }
        
        public string GetAttachFileName(string IndexString, string FieldName) {
            return base.Channel.GetAttachFileName(IndexString, FieldName);
        }
        
        public byte[] GetAttachFileBytes(string IndexString, string FieldName) {
            return base.Channel.GetAttachFileBytes(IndexString, FieldName);
        }
        
        public string GetFLWSFileName(string _indexString, string FieldName) {
            return base.Channel.GetFLWSFileName(_indexString, FieldName);
        }
        
        public byte[] GetFLWSFileBytes(string _indexString, string FieldName) {
            return base.Channel.GetFLWSFileBytes(_indexString, FieldName);
        }
        
        public System.Data.DataTable GetTaskQueryLog(string TaskID) {
            return base.Channel.GetTaskQueryLog(TaskID);
        }
        
        public bool ChangeQueryTaskRequestTime(string TaskID, System.DateTime RequestTime) {
            return base.Channel.ChangeQueryTaskRequestTime(TaskID, RequestTime);
        }
        
        public bool RebuildGuideLineParamSetting(string GuideLineID) {
            return base.Channel.RebuildGuideLineParamSetting(GuideLineID);
        }
        
        public SinoSZJS.Base.MetaData.Define.MD_QueryModel GetMDQueryModelDefine(string _queryModel) {
            return base.Channel.GetMDQueryModelDefine(_queryModel);
        }
        
        public System.Data.DataSet QueryData(SinoSZJS.Base.MetaData.QueryModel.MDQuery_Request mDQuery_Request) {
            return base.Channel.QueryData(mDQuery_Request);
        }
        
        public System.Data.DataTable GetMainTableDataByKey(string _queryModelName, string _mainTableName, string _keyid) {
            return base.Channel.GetMainTableDataByKey(_queryModelName, _mainTableName, _keyid);
        }
        
        public System.Data.DataTable GetChildTableDataByKey(string _queryModelName, string _childTableName, string _keyid) {
            return base.Channel.GetChildTableDataByKey(_queryModelName, _childTableName, _keyid);
        }
        
        public int GetChildTableCountByKey(string _queryModelName, string _childTableName, string _keyid) {
            return base.Channel.GetChildTableCountByKey(_queryModelName, _childTableName, _keyid);
        }
        
        public SinoSZJS.Base.MetaData.QueryModel.MDQuery_ChildTableRowCount[] GetChildRowCountList(string _queryModelName, string _keyid) {
            return base.Channel.GetChildRowCountList(_queryModelName, _keyid);
        }
        
        public SinoSZJS.Base.MetaData.Define.MD_ConceptGroup[] GetConceptList() {
            return base.Channel.GetConceptList();
        }
        
        public SinoSZJS.Base.MetaData.Define.MD_QueryModel[] GetQueryModels(string _queryModelNames) {
            return base.Channel.GetQueryModels(_queryModelNames);
        }
        
        public SinoSZJS.Base.MetaData.QueryModel.MDSearch_Column[] GetSearchResultColumn(string _searchText, int _searchType, string _searchConceptGroup, string _queryModelName) {
            return base.Channel.GetSearchResultColumn(_searchText, _searchType, _searchConceptGroup, _queryModelName);
        }
        
        public SinoSZJS.Base.MetaData.QueryModel.MDSearch_ResultDataIndex[] GetSearchResult(string _searchText, int _searchType, SinoSZJS.Base.MetaData.QueryModel.MDSearch_Column _sc) {
            return base.Channel.GetSearchResult(_searchText, _searchType, _sc);
        }
        
        public string GetMainTableKeyByChildKey(SinoSZJS.Base.MetaData.QueryModel.MDSearch_Column _childColumn, string _childKey) {
            return base.Channel.GetMainTableKeyByChildKey(_childColumn, _childKey);
        }
        
        public string GetMainTableKeyByColumnCondition(string _modelName, string _columnName, string _data) {
            return base.Channel.GetMainTableKeyByColumnCondition(_modelName, _columnName, _data);
        }
        
        public SinoSZJS.Base.MetaData.QueryModel.MD_GuideLine[] GetRootGuideLineList(string rootGuideLines) {
            return base.Channel.GetRootGuideLineList(rootGuideLines);
        }
        
        public SinoSZJS.Base.MetaData.QueryModel.MD_GuideLine[] GetGuideLineListByFatherID(string _fatherID) {
            return base.Channel.GetGuideLineListByFatherID(_fatherID);
        }
        
        public System.Data.DataTable QueryGuideLine(string _guideLineID, SinoSZJS.Base.MetaData.QueryModel.MDQuery_GuideLineParameter[] _param) {
            return base.Channel.QueryGuideLine(_guideLineID, _param);
        }
        
        public System.Data.DataTable QueryGuideLineByDefault(string _guideLineID, SinoSZJS.Base.MetaData.QueryModel.MDQuery_GuideLineParameter[] _param) {
            return base.Channel.QueryGuideLineByDefault(_guideLineID, _param);
        }
        
        public int QueryGuideLineResultCount(string _guideLineID, SinoSZJS.Base.MetaData.QueryModel.MDQuery_GuideLineParameter[] _params) {
            return base.Channel.QueryGuideLineResultCount(_guideLineID, _params);
        }
        
        public SinoSZJS.Base.MetaData.QueryModel.MD_GuideLine GetGuideLineByID(string _guideLineID) {
            return base.Channel.GetGuideLineByID(_guideLineID);
        }
        
        public string AddNewQueryTask(string _taskName, SinoSZJS.Base.MetaData.QueryModel.MDQuery_Request _queryRequest) {
            return base.Channel.AddNewQueryTask(_taskName, _queryRequest);
        }
        
        public SinoSZJS.Base.MetaData.QueryModel.MDQuery_Request GetQueryTaskRequestContext(string _taskID) {
            return base.Channel.GetQueryTaskRequestContext(_taskID);
        }
        
        public SinoSZJS.Base.MetaData.QueryModel.MDQuery_Task[] GetQueryTaskList() {
            return base.Channel.GetQueryTaskList();
        }
        
        public SinoSZJS.Base.MetaData.QueryModel.MDQuery_Task GetQueryTaskStateByID(string _taskID) {
            return base.Channel.GetQueryTaskStateByID(_taskID);
        }
        
        public bool ClearQueryTask(string _taskID) {
            return base.Channel.ClearQueryTask(_taskID);
        }
        
        public bool LockQueryTaskResult(string _taskID) {
            return base.Channel.LockQueryTaskResult(_taskID);
        }
        
        public bool CancleQueryTask(string _taskID) {
            return base.Channel.CancleQueryTask(_taskID);
        }
        
        public System.Data.DataSet GetTaskQueryResult_DataSet(string _taskID) {
            return base.Channel.GetTaskQueryResult_DataSet(_taskID);
        }
        
        public System.Data.DataSet GetTaskQueryResult_ORA(string _taskID) {
            return base.Channel.GetTaskQueryResult_ORA(_taskID);
        }
        
        public SinoSZJS.Base.MetaData.DataCheck.MD_CheckRule[] GetDataCheckRuleDefine(string QueryModelName) {
            return base.Channel.GetDataCheckRuleDefine(QueryModelName);
        }
        
        public void SaveQuery(string SaveName, bool IsPublic, SinoSZJS.Base.MetaData.QueryModel.MDQuery_Request QueryRequest) {
            base.Channel.SaveQuery(SaveName, IsPublic, QueryRequest);
        }
        
        public System.Data.DataTable GetSaveQueryList(string QueryModelName) {
            return base.Channel.GetSaveQueryList(QueryModelName);
        }
        
        public SinoSZJS.Base.MetaData.QueryModel.MDQuery_Request LoadQuery(string SaveQueryID) {
            return base.Channel.LoadQuery(SaveQueryID);
        }
        
        public System.Data.DataTable QueryDataWithWHXH(SinoSZJS.Base.MetaData.QueryModel.MDQuery_Request _queryRequest, string _dwdm) {
            return base.Channel.QueryDataWithWHXH(_queryRequest, _dwdm);
        }
        
        public SinoSZJS.Base.InputModel.MD_InputModel GetInputModelByName(string _modelName) {
            return base.Channel.GetInputModelByName(_modelName);
        }
        
        public bool DelSavedQuery(string _savedID) {
            return base.Channel.DelSavedQuery(_savedID);
        }
        
        public string GetUserLevel() {
            return base.Channel.GetUserLevel();
        }
        
        public System.Data.DataTable GetDataCheckInfo(string _modelName, string _mainKey, ref string SHID) {
            return base.Channel.GetDataCheckInfo(_modelName, _mainKey, ref SHID);
        }
        
        public string GetDataCheckInfoJLID(string QueryModelName, string _mainkeyId, string _level, ref string SHID) {
            return base.Channel.GetDataCheckInfoJLID(QueryModelName, _mainkeyId, _level, ref SHID);
        }
        
        public string SaveDataCheckResult(string CurrentJLID, string CurrentLevel, string CurrentID, string _shjg, string _shr, string _xgyj, string WHXH) {
            return base.Channel.SaveDataCheckResult(CurrentJLID, CurrentLevel, CurrentID, _shjg, _shr, _xgyj, WHXH);
        }
        
        public string GetDataCheckWHXH(string _tableName, string _mainColumn, string _mainKey) {
            return base.Channel.GetDataCheckWHXH(_tableName, _mainColumn, _mainKey);
        }
        
        public bool SaveNewDataCheckRule(string _ruleName, string _queryModelName, string _gzsf) {
            return base.Channel.SaveNewDataCheckRule(_ruleName, _queryModelName, _gzsf);
        }
        
        public bool DelDataCheckRule(string _ruleID) {
            return base.Channel.DelDataCheckRule(_ruleID);
        }
    }
}
