//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1022
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinoSZJS.Base.TokenService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TokenService.ITokenService")]
    public interface ITokenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenService/GetCurrentUser", ReplyAction="http://tempuri.org/ITokenService/GetCurrentUserResponse")]
        byte[] GetCurrentUser(string TokenTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenService/CheckTicket", ReplyAction="http://tempuri.org/ITokenService/CheckTicketResponse")]
        bool CheckTicket(string TokenTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenService/InsertToken", ReplyAction="http://tempuri.org/ITokenService/InsertTokenResponse")]
        bool InsertToken(string TokenTicket, byte[] AddUser);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITokenServiceChannel : SinoSZJS.Base.TokenService.ITokenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TokenServiceClient : System.ServiceModel.ClientBase<SinoSZJS.Base.TokenService.ITokenService>, SinoSZJS.Base.TokenService.ITokenService {
        
        public TokenServiceClient() {
        }
        
        public TokenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TokenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] GetCurrentUser(string TokenTicket) {
            return base.Channel.GetCurrentUser(TokenTicket);
        }
        
        public bool CheckTicket(string TokenTicket) {
            return base.Channel.CheckTicket(TokenTicket);
        }
        
        public bool InsertToken(string TokenTicket, byte[] AddUser) {
            return base.Channel.InsertToken(TokenTicket, AddUser);
        }
    }
}
